### DISCUSSION TITLE
【主题无关】【hexo技术相关】为什么在执行hexo d后无效

### DISCUSSION THREAD

**Discussion by luosiwei-cmd** [volantis-x/hexo-theme-volantis#583] [Q&A] [answered]
如题，在执行 hexo d 之后
![image](https://user-images.githubusercontent.com/61175380/107118252-c6982e80-68ba-11eb-9037-c40dbff2f0c8.png)
只显示如上图所示内容，部署到的仓库也没有反应，网站在 ctrl+F5 多次后也没有刷新。

求问是什么问题？

关于deploy 的配置如下：

```yaml
deploy: 
  type: git
  repo: https://e.coding.net/luosw-blog/luosw-blog.git
  branch: master
```
