### DISCUSSION TITLE
我们的主题在使用waline评论插件的时候，图片转base64失效

### DISCUSSION THREAD

**Discussion by TipsyDr** [volantis-x/hexo-theme-volantis#715] [Q&A] [answered]
发现利用我们的主题在使用waline评论插件的时候 会出现必须选在图床的情况 希望把waline里边调用uploadImage的部分调整成可配的

**Comment by penndu** [comment, marked as answer]
请参考
```
  waline:
    js: https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js
    path: # 全局评论地址 目前设置全局评论地址后visitor失效,这是waline的问题
    placeholder: 评论支持贴图，大家在截图后，在评论框粘贴，自动传至图床~  # 评论占位提示
    imageHosting: https://7bu.top/api/upload?token=9723fbead34e8263a16ef690c4622acc # 图床api（默认使用去不图床）
    # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder uploadImage] 选项
    meta: [nick,mail,link] # waline comment header info
    requiredFields: [nick,mail]
    serverURL: https://n.dusays.com # Waline 的服务端地址（必填） 测试用地址: https://waline-ruddy.vercel.app
    avatar: robohash # gravatar style https://waline.js.org/client/basic.html#avatar
    avatarCDN: #https://sdn.geekzu.org/avatar/
    emoji: [
      'https://dusays.com/gh/zhheo/Sticker-Heo@latest/Sticker-100/',
    ]
    pageSize: 10 # 评论每页显示数量
    lang: zh-CN
    visitor: true
```
