### DISCUSSION TITLE
侧边栏如何默认全部展开

### DISCUSSION THREAD

**Discussion by qiudaoermu** [volantis-x/hexo-theme-volantis#772] [Q&A]
现在侧边栏是滑到标题，才会展开第二级列表，全部展开怎么配置呢

**Comment by Tikas** [comment]
以前版本是全部展开的，或许增加一个配置选项会好一些

**Comment by MHuiG** [comment]
自己改一下样式吧

```css
#l_side .toc-wrapper .toc-child{
    max-height: unset !important;
}
```
