### DISCUSSION TITLE
cdn custom

### DISCUSSION THREAD

**Discussion by inkss** [volantis-x/hexo-theme-volantis#802] [General]
存在 name 值相同的时候，@MHuiG

https://github.com/volantis-x/hexo-theme-volantis/blob/6ac195f309843c86f22d5cecb6049216ef8f00e8/scripts/events/lib/cdn.js#L70

https://github.com/volantis-x/hexo-theme-volantis/blob/6ac195f309843c86f22d5cecb6049216ef8f00e8/_cdn.yml#L193-L206

**Comment by MHuiG** [comment]
system_config.custom[key]

**Reply by inkss** [reply]
不呀，priority: [custom, local, cdnjs, npm, static]，优先级上自定义的最高，但是这里你用 name 匹配，取不到值，然后不就落到下面的 cdnjs 里了。

![cdn js - Hexo-Blog - Visual Studio Code_22-08-21_08-42-33](https://user-images.githubusercontent.com/31947043/185770761-11e740fd-176b-4cae-9a8e-b0f0ec455012.png)

![cdn js - Hexo-Blog - Visual Studio Code_22-08-21_08-46-51](https://user-images.githubusercontent.com/31947043/185770800-164a1252-17ff-4e52-97c2-fcbdbece20b2.png)


![_cdn yml - Hexo-Blog - Visual Studio Code_22-08-21_08-45-42](https://user-images.githubusercontent.com/31947043/185770790-a044dc9f-eaf7-4d0f-90a0-9b7fb528d86e.png)

**Reply by MHuiG** [reply]
一个小时前改完了

**Reply by inkss** [reply]
哦哦  😂

**Reply by MHuiG** [reply]
https://github.com/volantis-x/hexo-theme-volantis/blob/6.0/scripts/events/lib/cdn.js#L111

**Reply by inkss** [reply]
local 不是读取本地文件的意思吗？却到了第三个 cdnjs 里

**Reply by MHuiG** [reply]
只有这几个有 local 属性

```yml
volantis_style:
  name: hexo-theme-volantis
  file: css/style.css
  local: true
  npm: false
  static: false
  cdnjs: false
volantis_app:
  name: hexo-theme-volantis
  file: source/js/app.js
  local: true
  npm: true
  static: false
  cdnjs: false
volantis_aplayer:
  name: hexo-theme-volantis
  file: source/js/plugins/aplayer.js
  local: true
  npm: true
  static: false
  cdnjs: false
volantis_parallax:
  name: hexo-theme-volantis
  file: source/js/plugins/parallax.js
  local: true
  npm: true
  static: false
  cdnjs: false
volantis_rightMenus:
  name: hexo-theme-volantis
  file: source/js/plugins/rightMenus.js
  local: true
  npm: true
  static: false
  cdnjs: false
volantis_tags_sites:
  name: hexo-theme-volantis
  file: source/js/plugins/tags/sites.js
  local: true
  npm: true
  static: false
  cdnjs: false
volantis_tags_friends:
  name: hexo-theme-volantis
  file: source/js/plugins/tags/friends.js
  local: true
  npm: true
  static: false
  cdnjs: false
volantis_tags_contributors:
  name: hexo-theme-volantis
  file: source/js/plugins/tags/contributors.js
  local: true
  npm: true
  static: false
  cdnjs: false
volantis_search_hexo:
  name: hexo-theme-volantis
  file: source/js/search/hexo.js
  local: true
  npm: true
  static: false
  cdnjs: false
```

**Reply by MHuiG** [reply]
cdnjs: false 都是 false 呀

**Reply by inkss** [reply]
比如我要是在 cdn.yml 这样子覆盖呢？

```yml
fancybox_js:
  name: "@fancyapps/ui"
  local: true
  file: source/js/szyink/fancybox.umd.js
```
