### DISCUSSION TITLE
关于分享时volantis的logo如何修改的问题

### DISCUSSION THREAD

**Discussion by HDILP** [volantis-x/hexo-theme-volantis#837] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/103124083/210475425-eae62603-c4b3-4192-8d37-f563edd835a7.png)
qq空间截图
![image](https://user-images.githubusercontent.com/103124083/210475468-1696197d-1753-4ccb-94e3-b1650c158f15.png)
钉钉截图

请问这个logo怎么修改

**Comment by Tikas** [comment]
分享获取的信息，是通过页面的 meta 标签来识别的，您可以查看自己的网站是否有指定 meta 相关信息，如果您对 meta 标签不了解，建议您先对它进行全面的了解之后，再来使用它。

另外，有很多专门的网站是来帮您生成 meta 信息的。

**Comment by BeaCox** [comment, marked as answer]
有些媒体在分享链接时会使用open graph（即开放图谱）协议
volantis提供了开放图谱协议的配置，详见当前仓库的`_config.yml`文件
```yaml
############################### Open Graph ############################### > start
# https://ogp.me/
# https://hexo.io/zh-cn/docs/helpers#open-graph
open_graph:
  image: volantis-static/media/org.volantis/blog/favicon/android-chrome-192x192.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/android-chrome-192x192.png
  twitter_card: summary # summary_large_image , summary
  #twitter_id:
  #twitter_site:
############################### Open Graph ############################### > end
```
将image配置为自己的logo即可
