### DISCUSSION TITLE
能否提供一下背景图？

### DISCUSSION THREAD

**Discussion by ncwzdlsd** [volantis-x/hexo-theme-volantis#839] [Q&A] [answered]
能否提供一下背景图？

**Comment by BeaCox** [comment, marked as answer]
详见[主题配置文件](https://github.com/volantis-x/hexo-theme-volantis/blob/6.0/_config.yml)
```yaml
# 视差滚动效果 Slide Background
  parallax:
    enable: #true
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 10000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - volantis-static/media/wallpaper/minimalist/2020/001.webp
      - volantis-static/media/wallpaper/minimalist/2020/002.webp
      - volantis-static/media/wallpaper/minimalist/2020/003.webp
      - volantis-static/media/wallpaper/minimalist/2020/004.webp
      - volantis-static/media/wallpaper/minimalist/2020/005.webp
      - volantis-static/media/wallpaper/minimalist/2020/006.webp
      - volantis-static/media/wallpaper/minimalist/2020/012.webp
      - volantis-static/media/wallpaper/minimalist/2020/016.webp
      - volantis-static/media/wallpaper/minimalist/2020/019.webp
      - volantis-static/media/wallpaper/minimalist/2020/025.webp
      - volantis-static/media/wallpaper/minimalist/2020/033.webp
      - volantis-static/media/wallpaper/minimalist/2020/034.webp
      - volantis-static/media/wallpaper/minimalist/2020/035.webp
      - volantis-static/media/wallpaper/minimalist/2020/038.webp
      - volantis-static/media/wallpaper/minimalist/2020/039.webp
      - volantis-static/media/wallpaper/minimalist/2020/042.webp
      - volantis-static/media/wallpaper/minimalist/2020/046.webp
      - volantis-static/media/wallpaper/minimalist/2020/051.webp
      - volantis-static/media/wallpaper/minimalist/2020/052.webp
      - volantis-static/media/wallpaper/minimalist/2020/054.webp
      - volantis-static/media/wallpaper/minimalist/2020/056.webp
```
上面就是官网使用的所有背景图，如果你仔细阅读过文档，应该知道`volantis-static`可以用`https://unpkg.com`替代。
当然你也可以去[volantis-static仓库](https://github.com/volantis-x/volantis-static/tree/main/media/wallpaper)查阅、下载背景图
