### ISSUE TITLE
关于使用之后的代码块样式问题

### ISSUE THREAD

**Issue by minewelt** [volantis-x/hexo-theme-volantis#127]
作者，你好
     首先，感谢你提供的优秀的主题，我很喜欢。
     但在使用过程中我也发现了一些问题。之前我使用的一款主题由于各种原因我修改了一些数值，换了你的主题之后应该是互不影响的，但是我发现代码块也随之改变了。这让我很苦恼。
![QQ图片20200131153042.png](https://i.loli.net/2020/01/31/Wo3snvYfA6rcQht.png)
      试了很久始终解决不了，麻烦你帮一下，毕竟只有你最了解它。
                                                                                                                                                      万分感谢

**Comment by xaoxuu** [comment]
目前主体不支持第三方的代码渲染插件，所以你可能之前用的是第三方插件。
你需要卸载已经安装的第三方代码渲染插件，然后在根目录的配置文件中找到并替换这段：

```
highlight:
  enable: true
  line_number: true  # 是否显示行数
  auto_detect: false
  tab_replace: "    "
```
