### ISSUE TITLE
Aplayer 无法正常工作

### ISSUE THREAD

**Issue by BedrockDigger** [volantis-x/hexo-theme-volantis#128]
未对/themes/material-x下任何文件做任何修改，生成后侧边栏无音乐插件显示，其他插件正常，（我猜）就是这几行由于某种原因没起作用？
``` yaml
- widget: music
    icon: fas fa-compact-disc
    title: "最近在听"
    more:
      icon: far fa-heart
      url: https://music.163.com/#/user/home?id=63035382
      rel: external nofollow noopener noreferrer
      target: _blank
    server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 2615636388     # 歌曲/专辑/歌单 ID
```
生成出根目录下的``index.html``中没这个section：
``` html
<section class='widget music'>
    
<header class='pure'>
  <div><i class="fas fa-compact-disc fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;推荐音乐</div>
  
    <a class="rightBtn"
    
      rel="external nofollow noopener noreferrer"
    
    
      target="_blank"
    
    href="https://music.163.com/#/user/home?id=35189854"
    title="https://music.163.com/#/user/home?id=35189854">
    <i class="far fa-heart fa-fw"></i></a>
  
</header>

    <div class='content pure'>
      
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.css">
  <div class="aplayer"
    data-theme="#1BCDFC"
    
    
    data-mode="circulation"
    data-server="netease"
    data-type="playlist"
    data-id="2945119589"
    data-volume="0.7">
  </div>
  <script src="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/meting@1.1.0/dist/Meting.min.js"></script>


    </div>
  </section>
```
（这个是我从其他用了侧边栏音乐插件的网友的``index.html``中``diff``出来发现我没有的
另外上面的yaml片段复制粘贴到一篇post的front-matter里作为专属可以BGM正常显示。

（本人前端小白，问题低级请多见谅

**Comment by TRHX** [comment]
你要在主题 `_config.yml` 文件里面进行配置，在 `layout - posts - sidebar` 选项里面，添加 `music` 关键字，`layout` 为布局，你可以添加或者去掉一些功能。
```
layout:
  # 文章列表（主页、自定义的列表）布局
  posts:
    # 列表中每一篇文章的meta信息
    meta: [title, author, date, categories, wordcount, top]
    # 列表类页面的侧边栏
    sidebar: [author, plain, list, grid, category, tagcloud, music]
```

**Comment by TRHX** [comment]
> 未对/themes/material-x下任何文件做任何修改，生成后侧边栏无音乐插件显示，其他插件正常，（我猜）就是这几行由于某种原因没起作用？
> 
> ```yaml
> - widget: music
>     icon: fas fa-compact-disc
>     title: "最近在听"
>     more:
>       icon: far fa-heart
>       url: https://music.163.com/#/user/home?id=63035382
>       rel: external nofollow noopener noreferrer
>       target: _blank
>     server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
>     type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
>     id: 2615636388     # 歌曲/专辑/歌单 ID
> ```
> 
> 生成出根目录下的`index.html`中没这个section：
> 
> ```
> <section class='widget music'>
>     
> <header class='pure'>
>   <div><i class="fas fa-compact-disc fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;推荐音乐</div>
>   
>     <a class="rightBtn"
>     
>       rel="external nofollow noopener noreferrer"
>     
>     
>       target="_blank"
>     
>     href="https://music.163.com/#/user/home?id=35189854"
>     title="https://music.163.com/#/user/home?id=35189854">
>     <i class="far fa-heart fa-fw"></i></a>
>   
> </header>
> 
>     <div class='content pure'>
>       
>   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.css">
>   <div class="aplayer"
>     data-theme="#1BCDFC"
>     
>     
>     data-mode="circulation"
>     data-server="netease"
>     data-type="playlist"
>     data-id="2945119589"
>     data-volume="0.7">
>   </div>
>   <script src="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.js"></script>
>   <script src="https://cdn.jsdelivr.net/npm/meting@1.1.0/dist/Meting.min.js"></script>
> 
> 
>     </div>
>   </section>
> ```
> 
> （这个是我从其他用了侧边栏音乐插件的网友的`index.html`中`diff`出来发现我没有的
> 另外上面的yaml片段复制粘贴到一篇post的front-matter里作为专属可以BGM正常显示。
> 
> （本人前端小白，问题低级请多见谅

你要在主题 `_config.yml` 文件里面进行配置，在 `layout - posts - sidebar` 选项里面，添加 `music` 关键字，`layout` 为布局，你可以添加或者去掉一些功能。
```
layout:
  # 文章列表（主页、自定义的列表）布局
  posts:
    # 列表中每一篇文章的meta信息
    meta: [title, author, date, categories, wordcount, top]
    # 列表类页面的侧边栏
    sidebar: [author, plain, list, grid, category, tagcloud, music]
```
