### ISSUE TITLE
代码框横向滑动时的UI问题

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#141]
## 描述
代码框里的代码较长时，如果横向滑动，顶部区域和左侧的 `line_number` 跟着一起滑动了。

## 重现
截图：

![](https://user-images.githubusercontent.com/16400144/75089825-b7c84700-5597-11ea-85ce-8358d3b019ab.png)

**Comment by inkss** [comment]
+1 发现，不过我那边是直接简单粗暴的将其放在了最右边，真的是眼不见心不烦系列

```css
.highlight .code:before {
    content: "";
    position: absolute;
    top: 0;
    right: 0;
    color: rgba(51, 51, 51, 0.8);
    font-size: 11.2px;
    padding: 2px 4px 0;
    line-height: 1.7;
}
```
