### ISSUE TITLE
1.7.4版本 hexo g 出现 keywords not defined 错误

### ISSUE THREAD

**Issue by TianZonglin** [volantis-x/hexo-theme-volantis#165]
## 描述
我目前已经将博客更新至1.7.4版本了，不过有个更新老是报错，而且我已经大概定位了出问题的更新：

- [优化SEO，front-matter支持seotitle](https://github.com/xaoxuu/hexo-theme-volantis/commit/b24b40670fcbef89df66476dbd9235da578453f7) 

其余全部正常。

## 重现
网址：
截图：

![image](https://user-images.githubusercontent.com/16513322/76045468-73f11c80-5f5d-11ea-951b-a09f41175030.png)

就这个错误，，head.ejs应该内容没错，因为我直接复制github上的内容也没法运行，报同样的错误。

现在回退也是这个错误了。。

**不过，**

虽然报错了，但文章页面看源代码的话，keywords是将tags写入的，

![image](https://user-images.githubusercontent.com/16513322/76045892-ac452a80-5f5e-11ea-9eab-c937eedd8b46.png)

本地测试有时网页能打开，但有时就是全白，然后console报那个错误。

## 环境

```
seo:
  # 当文章front-matter中没有keywords时，使用tags作为keywords
  use_tags_as_keywords: true
  # 当文章front-matter中没有description时，使用摘要作为description
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
```

### 已解决

把原先keywords的定义那行给删掉了。。。
