### ISSUE TITLE
关于封面页的那个那个小箭头

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#177]
## 描述
就是那个向下翻页的小箭头, 在按下后下翻到主体页, 但是还能透过Sidebar的半透明效果看到它在那里上下浮动, 感觉有点不太好看, 建议能不能向下翻页后将其隐藏

> **注**
>
> 由于不同浏览器对透明效果处理的不同, Chrome下透明效果不清晰, 但是Firefox就很清晰了

## 重现
网址：https://volantis.js.org
截图：![BUG](https://s1.ax1x.com/2020/03/13/8umBgx.png)

## 环境
Hexo版本：
`package.json`文件：
根目录的`_config.yml`文件：（敏感数据请替换为****）
主题的`_config.yml`文件：

**Comment by xaoxuu** [comment]
😂我不想搞了，你自己调成半透明的不怪我

**Comment by Reqwey** [comment]
是你的官网欸🤣

**Comment by xaoxuu** [comment]
我的不应该是毛玻璃效果吗，怎么没有了

**Comment by Reqwey** [comment]
不知道啊, 感觉Firefox变成了半透明

**Comment by Reqwey** [comment]
感觉半透明更好看耶( •̀ ω •́ )y

**Comment by xaoxuu** [comment]
<img width="1311" alt="截屏2020-03-1314 54 31" src="https://user-images.githubusercontent.com/16400144/76597035-8dd0c780-653a-11ea-9252-feac61783fc1.png">

**Comment by Reqwey** [comment]
你是Chrome吧

**Comment by xaoxuu** [comment]
```
navbar:
    height: 64px
    effect: [blur] # [shadow, floatable, blur]
  sidebar:
    effect: [blur] # [shadow, floatable, blur]
  body:
    effect: [blur] # [shadow, floatable, blur]
```
你试一下这样，把 `effect` 部分全部设置成纯 `blur` 效果看看是半透明还是毛玻璃，我见过 `floatable` 效果卡片浮起来的时候阴影部分会变成半透明，没想到你那里看全部都是半透明。
