### ISSUE TITLE
分类和标签，点击具体的某个分类和标签时404

### ISSUE THREAD

**Issue by HaleShaw** [volantis-x/hexo-theme-volantis#181]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

大的分类和标签可以正常显示，如;
`https://www.jianwudao.com/categories`
但是再深一层的具体分类或标签就显示404。
有看生成的文件，目录下有index.html。
在本地`hexo s`起来的时候是正常的，部署到github上就不行了。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Expected behavior 
点击任意具体分类或具体标签，都能正常访问页面。

## Actual behavior 

- Links to demo site with this issue: https://www.jianwudao.com/categories/soft/
- Links to repository or source code of the blog: https://github.com/HaleShaw/HaleShaw.github.io

## Steps to reproduce the behavior 
1. 点击具体的某个分类或者具体的某个标签

### Node.js and NPM Information

```
v12.16.1
6.13.4
```

### Package dependencies Information

```
+-- UNMET PEER DEPENDENCY hexo@4.2.0
+-- hexo-all-minifier@0.5.3
+-- hexo-autonofollow@1.0.1
+-- hexo-autoprefixer@1.0.0
+-- hexo-deployer-git@2.1.0
+-- hexo-fs@2.0.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-json-content@4.1.6
+-- hexo-generator-search@2.4.0
+-- hexo-generator-seo-friendly-sitemap@0.0.25
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-qrcode@1.0.2
+-- hexo-lazyload-image@1.0.6
+-- hexo-offline@1.0.0
+-- hexo-related-popular-posts@4.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-less@1.0.0
+-- hexo-renderer-markdown-it@4.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-wordcount@6.0.1
+-- markdown-it-abbr@1.0.4
+-- markdown-it-checkbox@1.1.0
+-- markdown-it-container@2.0.0
+-- markdown-it-deflist@2.0.3
+-- markdown-it-emoji@1.4.0
+-- markdown-it-footnote@3.0.2
+-- markdown-it-imsize@2.0.1
+-- markdown-it-ins@3.0.0
+-- markdown-it-mark@3.0.0
+-- markdown-it-regexp@0.4.0
+-- markdown-it-sub@1.0.0
+-- markdown-it-sup@1.0.0
`-- markdown-it-task-checkbox@1.0.6

npm ERR! peer dep missing: hexo@^3.2.2, required by hexo-offline@1.0.0
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 剑无道
subtitle: 无极之道
description: '断剑无锋，天元轮回。流光咫尺，刹那芳华！'
keywords: '剑无道,博客,软件,Hexo,Hexo博客'
author: Hale
language: zh-CN
timezone: ''
favicon: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/favicon_16.ico
avatar: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/log/16/avatar.png

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.jianwudao.com
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis


# Deployment
## Docs: https://hexo.io/docs/deployment.html
# npm install hexo-deployer-git --save
deploy:
  - type: git
    repo: git@github.com:HaleShaw/HaleShaw.github.io.git
    branch: master
    message: "Github CI Auto Builder at {{ now('YYYY-MM-DD HH:mm:ss Z') }}"
# ssh-keygen -t rsa -b 4096 -C "HaleShaw@163.com" -N "" -f deploy_key


use_cdn: false

# 全局导入
import:
  meta:
  - "<meta name='theme-color' content='#FFFFFF'>"
  - "<meta name='msapplication-TileColor' content='#1BC3FB'>"
  - "<meta name='msapplication-config' content='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/favicon/browserconfig.xml'>"
  link:
  # - "<link rel='shortcut icon' type='image/x-icon' href='https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/favicon_16.ico'>"
  - "<link rel='icon' type='image/x-icon' sizes='32x32' href='https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/favicon_32.ico'>"
  - "<link rel='apple-touch-icon' type='image/png' sizes='180x180' href='https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/favicon_180.png'>"
  - "<link rel='mask-icon' color='#1BC3FB' href='https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/favicon_512.svg'>"
  - "<link rel='manifest' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/favicon/site.webmanifest'>"
  # script:

# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false

# 图片懒加载  # hexo-lazyload-image    hexo-fs
lazyload:
  enable: true
  onlypost: false
  loadingImg: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/lazyLoad.svg


# hexo-all-minifier
all_minifier: true

# hexo-autonofollow
nofollow:
  enable: true
  exclude:
  - xaoxuu.com
  - volantis.js.org

# autoprefixer
autoprefixer:
  exclude:
  - '*.min.css'

# offline config passed to sw-precache.
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-deflist
    - markdown-it-imsize
    - markdown-it-mark
    - markdown-it-regexp
    - markdown-it-task-checkbox
    - name: markdown-it-container
      options: success
    - name: markdown-it-container
      options: info
    - name: markdown-it-container
      options: warning
    - name: markdown-it-container
      options: danger
    - markdown-it-deflist
    - name: markdown-it-emoji
      options:
        shortcuts: {}
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: ''

```

### Volantis Configuration

```yml
############################### Basic Information ###############################
info:
  name: Volantis
  version: '2.1.4'
  docs: https://volantis.js.org/
  cdn: # To use CDN, write 'use_cdn: true' in 'blog/_config.yml'.
    css: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.1.4.1/css/style.css
    js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.1.4/js/app.js


############################### Style ###############################
style:
  max_width: 1080px # Sum of body width and sidebar width
  navbar:
    height: 64px
    effect: [shadow, blur] # [shadow, floatable, blur]
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
    highlight:
      language: true # show language of codeblock
      copy_btn: true
    text_align: # left, right, justify, center
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
  gap:
    h2: 48px # Spacing above H2 (only px unit)
    h3: 32px # Spacing above H3 (only px unit)
    h4: 16px # Spacing above H4 (only px unit)
    line: 1rem # Paragraph spacing
    inline: .5rem # Paragraph spacing within a block
  border_radius:
    card: 12px
    codeblock: 4px
    searchbar: 8px
    button: 4px
  tabs:
    shadow_level: 1 # 0, 1, 2, 3
  fontsize:
    root: 16px
    h1: 1.625rem
    h2: 1.375rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    body: 1rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .75rem
  fontfamily:
    bodyfont:
      name: 'Varela Round'
      url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    # codefont:
    #   name: 'Monaco'
    #   url: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-fonts/Monaco/Monaco.ttf
    #   weight: normal
    #   style: normal
    titlefont:
      name: 'JianWudaoMaoBi'
      url: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/font/JianWudaoMaoBi.ttf
      weight: normal
      style: normal
  # color:
  #   site: '#21232F' # Website background color
  #   card: '#444' # Card background color
  #   text: '#fff' # The color of the text on the card.
  #   theme: '#ff9800' # Main color
  #   link: '#1BCDFC' # Link color
  #   hover: '#ff5722' # Link highlight color
  #   inner: '#333' # Text color inside the button
  #   block: '#555' # Block color
  #   inlinecode: yellow # Inline code color
  #   codeblock: '#555' # Codeblock color
  #   p: '#ccc' # Paragraph color




############################### Layout ###############################
cover:
  scheme: docs # docs, blog
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  logo: # https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/256/google_logo.png
  title: 剑无道
  subtitle: ''
  search: # search bar placeholder
  features:
    - name: 博文
      icon: fas fa-file-alt
      url: /
    - name: 软件
      icon: fas fa-tools
      url: tools/
    - name: 友链
      icon: fas fa-link
      url: links/
    - name: 关于
      icon: fas fa-info-circle
      url: about/


# Navigation Bar
navbar:
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title: 剑无道
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
    # This menu will be displayed on the laptop or desktop.
    on_desktop:
      - name: 首页
        icon: fas fa-home
        url: /
      - name: 软件
        icon: fas fa-tools
        url: tools/
      - name: 分类
        icon: fas fa-folder-open
        url: categories/
      - name: 归档
        icon: fas fa-archive
        url: archives/
      - name: 关于
        icon: fas fa-info-circle
        url: about/

    # This menu will be displayed on the mobile.
    on_mobile:
      - name: 博文
        icon: fas fa-clock
        url: /
      - name: 归档
        icon: fas fa-archive
        url: archives/
      - name: 友链
        icon: fas fa-link
        url: links/
      - name: 关于
        icon: fas fa-info-circle
        url: about/
  search: 搜索   # Search bar placeholder



layout:
  # The following can be written in `blog/source/_data/layout.yml`
  # 文章列表（主页、自定义的列表）布局
  on_list:
    # 列表中每一篇文章的meta信息
    meta: [title, author, category, date, wordcount, top]
    # 列表类页面的侧边栏
    sidebar: [blogger, category, tagcloud, donate]
    # read more button
    readmore: Read More <i class="fas fa-chevron-right"></i>
  # 页面布局
  on_page:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    meta:
      header: [title, author, category, date, top]
      footer: [updated, tags, btns, share]
    # 文章页面的侧边栏
    sidebar: [toc, related_posts, category, tagcloud, donate]
  # 文章布局，参数继承自 on_page
  on_post:
    # 文章页脚，自动在每一篇文章末尾添加
    article_footer: [copyright, donate]
  # 其他的页面布局暂时等于 on_list


# meta library
meta:
  # 文章标题
  title: # 暂无配置
  # 默认文章作者（可在front-matter中覆盖）
  author:
    avatar: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/log/16/avatar.png
    name: Hale Shaw
    url: https://jianwudao.com
  # 文章创建日期
  date:
    icon: fas fa-edit
    title: '发布于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章更新日期
  updated:
    icon: fas fa-save
    title: '更新于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章分类
  category:
    icon: fas fa-folder-open
  # 文章置顶
  top:
    icon: fas fa-angle-double-up
  # 文章浏览计数
  counter:
    icon: fas fa-eye
  # 文章字数和阅读时长
  wordcount:
    icon_wordcount: fas fa-keyboard
    icon_duration: fas fa-hourglass-half
  # 文章标签
  tags:
    icon: fas fa-hashtag
  # 分享
  share:
    - id: qq
      img: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/logo/128/qq.png
    - id: qzone
      img: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/logo/128/qzone.png
    - id: weibo
      img: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/logo/128/weibo.png
    - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
      img: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/logo/32/qrcode.png
  # 链接
  btns:
    edit:
      icon: fas fa-edit
      title: 在GitHub上编辑此页
      color: '#888'
    repo: # 源码链接
      icon: fas fa-file-code
      title: 源码
      color: '#508EF2'
    bug: # BUG反馈链接
      icon: fas fa-bug
      title: BUG
      color: '#FE5F58'
    doubt: # 疑问链接
      icon: fas fa-question-circle
      title: 疑问
      color: '#FFBD2B'
    idea: # 建议链接
      icon: fas fa-lightbulb
      title: 建议
      color: '#3DC550'
    faq: # FAQ链接
      icon: fas fa-comments
      title: FAQ
      color: '#29B1C9'
    feedback: # 反馈链接
      icon: fas fa-comment-dots
      title: 反馈
      color: '#1BCDFC'

# widget library
widget:
  # The following can be written in `blog/source/_data/widget.yml`
  # ---------------------------------------
  # blogger info widget
  blogger:
    class: blogger
    display: [desktop] # [desktop, mobile]
    avatar: https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/avatar_450.jpg
    title:
    subtitle:
    jinrishici: 断剑无锋，天元轮回。
    social: true
  # ---------------------------------------
  # toc widget (valid only in articles)
  toc:
    class: toc
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-list
      title: 本文目录
    list_number: false
    min_depth: 2
    max_depth: 5
  # ---------------------------------------
  # category widget
  category:
    class: category
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-folder-open
      title: 文章分类
      url: /categories/
  # ---------------------------------------
  # tagcloud widget
  tagcloud:
    class: tagcloud
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-tags
      title: 热门标签
      url: /tags/
    min_font: 14
    max_font: 24
    color: true
    start_color: '#999'
    end_color: '#555'
  # ---------------------------------------
  # related posts widget
  related_posts:
    class: related_posts # npm i -S hexo-related-popular-posts
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-bookmark
      title: 相关文章
    max_count: 5
  # ---------------------------------------
  # copyright widget (valid only in articles)
  copyright:
    class: copyright
    display: [desktop, mobile] # [desktop, mobile]
    blockquote: true
    permalink: '本文永久链接是：'
    content:
      - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
      - permalink
  # ---------------------------------------
  # qrcode widget
  donate:
    class: qrcode
    display: [desktop, mobile] # [desktop, mobile]
    height: 64px  # Automatic height if not set
    fancybox: true
    images:
      - https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/qrcode/donate_Alipay.png
      - https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/qrcode/donate_Wechat.jpg
  # You can add your own widget here or 'blog/source/_data/widget.yml'
  # class: text, list, grid, qrcode, page, ... see more at https://volantis.js.org/



footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, info, copyright]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:HaleShaw@163.com
    - icon: fab fa-github
      url: https://github.com/HaleShaw
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=272489364
  copyright: '[Copyright © 2015-2020 JianWudao](https://jianwudao.com)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'


############################### SEO ###############################
seo:
  # When there are no keywords in the article's front-matter, use tags as keywords.
  use_tags_as_keywords: true
  # When there is no description in the article's front-matter, use excerpt as the description.
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
    # robots can be written in front-matter


############################### Plugins ###############################
plugins:
  # Required plugins:
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.4/dist/jquery.min.js

  ######## Plugins to improve loading speed:
  # Preload (The menu's url must end with ‘/’)
  instant_page: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/instant_page.js

  ######## Plugins to optimize the experience:
  # Picture Zoom
  fancybox:
    css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
    js: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  # Page Scrolling Animation
  scrollreveal: #https://cdn.jsdelivr.net/npm/scrollreveal@4.0.5/dist/scrollreveal.min.js

  # Codeblock Copy Button
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  # mathjax
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  ######## Plugins for SEO:
  # Traffic statistics (very slow loading)
  busuanzi: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js

  # npm i --save hexo-wordcount
  wordcount: #true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

  # Typing Effects
  comment_typing: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/comment_typing.js

  # Slide Background
  backstretch:
    enable: true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 20000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    white_text: #true     # Whether the picture is dark (adjust the text to white)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/blog_bg_01.jpg
      - https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/blog_bg_02.jpg
      - https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/blog_bg_03.jpg
      - https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/blog_bg_04.jpg
      - https://cdn.jsdelivr.net/gh/HaleShaw/cdn/img/blog_bg_05.jpg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/00E0F0ED-9F1C-407A-9AA6-545649D919F4.jpeg
      # # Suggest white_text: true
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B951AE18-D431-417F-B3FE-A382403FF21B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/AEB33F9D-7294-4CF1-B8C5-3020748A9D45.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/2884F904-F1F3-479E-AE27-5EBC291B63B0.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/10A0FCE5-36A1-4AD0-8CF0-019259A89E03.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/250662D4-5A21-4AAA-BB63-CD25CF97CFF1.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/298468D7-E388-44A8-8CC5-8213BDC33CED.jpeg

  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: true
    js:
      - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
      - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 373455763    # song id / playlist id / album id / search keyword
    # Optional
    fixed: false      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 340px # list max height
    list_folded: true




############################### Comments ###############################
comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: valine # valine, disqus, gitalk, livere
  valine:
    appId: 
    appKey: 
    js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.0/js/valine.js
    path: # All pages use the same path (share the same comments data)
    meta: nick,mail,link #valine comment header info
    placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
    avatar: mp # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    verify: true # valine verify code (true/false)
    notify: true # valine mail notify (true/false)
    lang: zh-cn
    highlight: true
    visitor: false # unavailable for now...
  disqus:
    shortname:
  gitalk:
    clientID:
    clientSecret:
    repo:
    owner:
    admin: # []
  livere:
    uid:




############################### Search ###############################
# To use hexo search, you need to install the following plugins:
# npm i -S hexo-generator-search hexo-generator-json-content
search:
  enable: true
  service: hexo  # hexo, google, algolia, azure, baidu
  js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.1/js/search.js
  google:
    apiKey:
    engineId:
  algolia:
    applicationID:
    apiKey:
    indexName:
  azure:
    serviceName:
    indexName:
    queryKey:
  baidu:
    apiId:

```
