### ISSUE TITLE
手机博客页面，菜单栏无效

### ISSUE THREAD

**Issue by ChemLez** [volantis-x/hexo-theme-volantis#187]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Expected behavior 
手机端不能展示出菜单栏

## Actual behavior 

- Links to demo site with this issue: https://www.liizhi.cn/
- Links to repository or source code of the blog: https://github.com/ChemLez/volantis-docs

## Steps to reproduce the behavior 
1. 修改了主题的配置文件
2.  source/_data 并未相应配置文件

### Node.js and NPM Information

```
sh-3.2# node -v && npm -v
v12.14.1
6.14.2
```

### Package dependencies Information

```
sh-3.2# npm ls --depth 0
hexo-site@0.0.0 /Users/liz/Documents/Blog
├── UNMET PEER DEPENDENCY hexo@4.2.0
├── hexo-deployer-git@2.1.0
├── hexo-fs@2.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-json-content@4.1.6
├── hexo-generator-search@2.4.0
├── hexo-generator-tag@1.0.0
├── hexo-helper-qrcode@1.0.2
├── hexo-lazyload-image@1.0.6
├── hexo-offline@1.0.0
├── hexo-related-popular-posts@4.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
└── hexo-wordcount@6.0.1
npm ERR! peer dep missing: hexo@^3.2.2, required by hexo-offline@1.0.0
sh-3.2# 
```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml
    # This menu will be displayed on the mobile.
    on_moblie:
      - name: 近期文章
        icon: fas fa-clock fa-fw
        url: /
      - name: 文章归档
        icon: fas fa-list-alt fa-fw
        url: archives/
      - name: 文章类别
        icon: fas fa-folder-open
        url: categories/
      - name: 我的友链
        icon: fas fa-link
        url: friends/
      - name: 关于小站
        icon: fas fa-info-circle
        url: about/
```
