### ISSUE TITLE
评论无法使用问题

### ISSUE THREAD

**Issue by WPF0414** [volantis-x/hexo-theme-volantis#204]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 
您好作者，使用最新版主题，选择评论为valine，配置好app_id和app_key后无效果，并没有展示评论，请问下是什么原因？本人不是太懂，希望作者帮忙，谢谢！

**Comment by xaoxuu** [comment]
如果是从旧版本更新而来的，部分属性名大小写改成和 Valine 官方一致的了，在主题配置文件中**直接填写**即可。

```
comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: valine # valine, disqus, gitalk, livere
  valine:
    appId: # your appId
    appKey: # your appKey
```
