### ISSUE TITLE
Valine评论验证码问题

### ISSUE THREAD

**Issue by jiahao-jayden** [volantis-x/hexo-theme-volantis#212]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Expected behavior 
正常使用评论，并且可以使用验证码

## Actual behavior 

- Links to demo site with this issue: https://mrhuanhao.cn/
输入验证码的时候，没有显示验证码，图中没有显示数字，实际我已经输入了
![image.png](https://i.loli.net/2020/04/03/gHixqFKCQyJu61b.png)

**正常情况应该如图所示：**
![image.png](https://i.loli.net/2020/04/03/S26gUptycFdkXoV.png)

### Node.js and NPM Information

```
6.13.4
```

### Hexo Configuration

```yml
comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: valine # valine, disqus, gitalk, livere
  valine:
    appId:   # your appId
    appKey: # your appKey
    js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.4/js/valine.js
    path: # All pages use the same path (share the same comments data)
    meta: nick,mail,link #valine comment header info
    placeholder: 如果你有什么疑问或者吐槽，快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
    avatar: mp 
    pageSize: 10 
    verify: true 
    notify: true 
    lang: zh-cn
    highlight: true
    visitor: false # unavailable for now...
```
