### ISSUE TITLE
评论系统如何开启？

### ISSUE THREAD

**Issue by LiYanan2004** [volantis-x/hexo-theme-volantis#23]
如题，一直失败

**Comment by xaoxuu** [comment]
你要用哪种评论系统去对应的官网看文档进行配置。[https://xaoxuu.com/wiki/material-x/#评论系统](https://xaoxuu.com/wiki/material-x/#%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F)

**Comment by LiYanan2004** [comment]
主目录下的config怎么设置啊，用的是Valine

**Comment by xaoxuu** [comment]
就把我文档里的示例copy过去，然后把`appId`和`appKey`改成你自己的就可以了，别的不需要改。
```yaml
# valine
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  appId:  # 必填
  appKey:  # 必填
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn
```
如果不知道怎么获取id和key，valine官网有详细的教程：https://valine.js.org/quickstart.html
