### ISSUE TITLE
小白上线！readmore按钮出不来！

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#239]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 
大佬你好，小白上线！文章列表怎么样才能出现readmore按钮呢？搭半天还是出不来噢，请你指导指导，谢谢！

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

  # 文章列表（主页、自定义的列表）布局
  on_list:
    # 列表中每一篇文章的meta信息
    meta: [title, author, category, date, wordcount, top]
    # 列表类页面的侧边栏
    sidebar: [blogger, category, tagcloud, qrcode]
    # read more button
    readmore: Read More <i class="fas fa-chevron-right"></i>
```

## Other Information 
这里倒是有一个readmore，但好像不行。
