### ISSUE TITLE
关于颜色自定义(;ŏ﹏ŏ)

### ISSUE THREAD

**Issue by RimuruW** [volantis-x/hexo-theme-volantis#252]
## Issue Checklist 

- [ × ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ × ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ × ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Expected behavior 
在主题配置文件 _config.yml 中自定义颜色，颜色应根据我输入的十六进制颜色码转换成相应的 RGB 颜色值。

## Actual behavior 

颜色并未发生任何改变。

## Steps to reproduce the behavior 
hexo clean && hexo g -d

## Environment Information
Termux，Android Q
Deploy by GitHub Action.
### Node.js and NPM Information

```
v13.0.0
v6.14.4
```

### Package dependencies Information

```
hexo-site@0.0.0 /data/data/com.termux/files/home/GA
├── canvas-nest.js@2.0.4
├── UNMET PEER DEPENDENCY hexo@4.2.0
├── hexo-admin@2.3.0
├── hexo-blog-encrypt@3.0.12
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-baidu-sitemap@0.1.6
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-json-content@4.2.3
├── hexo-generator-searchdb@1.2.0
├── hexo-generator-sitemap@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-less@0.1.0
├── hexo-neat@1.0.4
├── hexo-offline@1.0.0
├── hexo-related-popular-posts@4.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-less@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
├── hexo-symbols-count-time@0.7.1
└── hexo-wordcount@6.0.1

npm ERR! peer dep missing: hexo@^3.2.2, required by hexo-offline@1.0.0
```
### Hexo Configuration

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Qingxu's Blog
subtitle: '人生如逆旅，我亦是行人'
description: '你也一定是一个璀璨如星 明澈如水的人'
keywords: Qingxu's Blog
author: Qingxu
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://huanruomengyun.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis
plugins: hexo-generate-feed
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:huanruomengyun/huanruomengyun.github.io.git
  branch: master
#本地搜索
search: 
  path: search.xml
  field: post
  formal: html
  limit: 10000

#feed
feed: 
  type: atom 
  path: atom.xml 
  limit: 20 
  hub: 
  content: 
  content_limit: 
  content_limit_delim: ' '

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 4
  wpm: 275
  suffix: "mins."
 

favicon: images/favicon.png

## offline config passed to sw-precache.
offline:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
```

### Volantis Configuration

```
    color:
      site: '#21232F'
      site_inner: '#fff'
      site_footer: '#85C1E9' 
      card: '#444' 
      text: '#fff' 
      theme: '#ff9800' 
      link: '#2471a3' 
      hover: '#1A5276' 
      inner: '#333' 
      block: '#D5D8DC' 
      inlinecode: '#ABB2B9' 
      codeblock: '#566573'
      p: '#ccc'
```

## Other Information 
Browser：Chrome
System： Both Android and Arch Linux
