### ISSUE TITLE
文章目录异常

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#266]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Expected behavior 
![image](https://user-images.githubusercontent.com/62386802/80861426-177e5500-8ca1-11ea-9d34-123994bbea3c.png)
这是另外一篇文章，目录h2标题显示正常

## Actual behavior 

![image](https://user-images.githubusercontent.com/62386802/80861470-53b1b580-8ca1-11ea-8310-c1718bc195c1.png)
h2标题左边带一个点，没有加粗，h3变成主标题

- Links to demo site with this issue: https://www.flexiston.com/build-a-hexo-site-1/

## Steps to reproduce the behavior 
1. 文章添加h2标题

### Node.js and NPM Information

```
v12.16.1
6.13.4
```

### Package dependencies Information

```
+-- cheerio@0.19.0
`-- nodemailer@6.4.6

npm ERR! extraneous: domutils@1.5.1 C:\Users\Andy\node_modules\htmlparser2\node_modules\domutils
npm ERR! extraneous: entities@1.0.0 C:\Users\Andy\node_modules\htmlparser2\node_modules\entities
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Flexiston's Notes
subtitle: ''
description: ''
keywords: 
author: Flexiston
language: zh-CN
timezone: ''
email: flexiston@163.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.flexiston.com
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: git@e.coding.net:****/****.git
    branch: master
  - type: baidu_url_submitter

favicon: /favicon.ico

use_cdn: true

# Sitemap
sitemap:
  path: sitemap.xml

# RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: /favicon.ico
  autodiscovery: true
  template:

# Auto No Follow
nofollow:
  enable: true
  exclude:

# Lazyload Images
lazyload:
  enable: true
  onlypost: false
  loadingImg: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/placeholder/f107c4d98691c0e2f4592acf09f83acb46fdf7.svg # eg ./images/loading.gif
```

### Volantis Configuration

```yml
############################### Layout ###############################
cover:
  scheme: blog # docs, blog
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  logo: # https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/256/google_logo.png
  title: Flexiston
  subtitle: ''
  search: # search bar placeholder
  features:
    - name: 首页
      icon: fas fa-home
      url: /
    - name: 归档
      icon: fas fa-archive
      url: /archives/
    - name: 关于
      icon: fas fa-info-circle
      url: /about/
    - name: RSS
      icon: fas fa-rss
      url: /atom.xml
      target: _blank


# Navigation Bar
navbar:
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title: Flexiston's Notes
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
    - name: 博客
      icon: fas fa-rss
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
  search: 搜索...   # Search bar placeholder



layout:
  # The following can be written in `blog/source/_data/layout.yml`
  # 文章列表（主页、自定义的列表）布局
  on_list:
    # 列表中每一篇文章的meta信息
    meta: [title, author, category, date, wordcount, top]
    # 列表类页面的侧边栏
    sidebar: [blogger, category, tagcloud, qrcode]
    # read more button
    readmore: Read More <i class="fas fa-chevron-right"></i>
  # 页面布局
  on_page:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    meta:
      header: [title, author, category, date, top]
      footer: [updated, tags, btns, share]
    # 文章页面的侧边栏
    sidebar: [qrcode, toc]
  # 文章布局，参数继承自 on_page
  on_post:
    # 文章页脚，自动在每一篇文章末尾添加
    article_footer: [references, related_repos, copyright, donate]
  # 其他的页面布局暂时等于 on_list


# meta library
meta:
  # 文章标题
  title: # 暂无配置
  # 默认文章作者（可在front-matter中覆盖）
  author:
    avatar:
    name: Flexiston
    url: https://www.flexiston.com
  # 文章创建日期
  date:
    icon: fas fa-calendar-alt
    title: '发布于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章更新日期
  updated:
    icon: fas fa-edit
    title: '更新于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章分类
  category:
    icon: fas fa-folder-open
  # 文章置顶
  top:
    icon: fas fa-angle-double-up
  # 文章浏览计数
  counter:
    icon: fas fa-eye
  # 文章字数和阅读时长
  wordcount:
    icon_wordcount: fas fa-keyboard
    icon_duration: fas fa-hourglass-half
  # 文章标签
  tags:
    icon: fas fa-hashtag
  # 分享
  share:
    - id: qq
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qq.png
    - id: qzone
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qzone.png
    - id: weibo
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/weibo.png
    # - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
    #   img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/wechat.png
    # - id: telegram
    #   img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/telegram.png
  # 链接
  btns:
    #edit:
      #icon: fas fa-edit
      #title: 在GitHub上编辑此页
      #color: '#888'
    #repo: # 源码链接
      #icon: fas fa-file-code
      #title: 源码
      #color: '#508EF2'
    #bug: # BUG反馈链接
      #icon: fas fa-bug
      #title: BUG
      #color: '#FE5F58'
    #doubt: # 疑问链接
      #icon: fas fa-question-circle
      #title: 疑问
      #color: '#FFBD2B'
    #idea: # 建议链接
      #icon: fas fa-lightbulb
      #title: 建议
      #color: '#3DC550'
    #faq: # FAQ链接
      #icon: fas fa-comments
      #title: FAQ
      #color: '#29B1C9'
    #feedback: # 反馈链接
      #icon: fas fa-comment-dots
      #title: 反馈
      #color: '#1BCDFC'

# widget library
widget:
  # The following can be written in `blog/source/_data/widget.yml`
  # ---------------------------------------
  # blogger info widget
  blogger:
    class: blogger
    display: [desktop, mobile] # [desktop, mobile]
    avatar: 
    shape: rectangle # circle, rectangle
    url: /about/
    title:
    subtitle:
    jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
    social: true
  # ---------------------------------------
  # toc widget (valid only in articles)
  toc:
    class: toc
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-list
      title: 本文目录
    list_number: false
    min_depth: 2
    max_depth: 5
  # ---------------------------------------
  # category widget
  category:
    class: category
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-folder-open
      title: 文章分类
      url: /categories/
  # ---------------------------------------
  # tagcloud widget
  tagcloud:
    class: tagcloud
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-tags
      title: 热门标签
      url: /tags/
    min_font: 14
    max_font: 24
    color: true
    start_color: '#999'
    end_color: '#555'
  # ---------------------------------------
  # related posts widget
  related_posts:
    class: related_posts # npm i -S hexo-related-popular-posts
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-bookmark
      title: 相关文章
    max_count: 5
  # ---------------------------------------
  # copyright widget (valid only in articles)
  copyright:
    class: copyright
    display: [desktop, mobile] # [desktop, mobile]
    blockquote: true
    permalink: '本文永久链接是：'
    content:
      - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
      - permalink
  # ---------------------------------------
  # qrcode widget
  donate:
    class: qrcode
    display: [desktop, mobile] # [desktop, mobile]
    height: 140px  # Automatic height if not set
    fancybox: false
    images:
  # ---------------------------------------
  # references widget
  #references:
    #class: references # is subclass of list
    #display: [desktop, mobile] # [desktop, mobile]
    #header:
      #icon: fas fa-quote-left
      #title: 参考资料
  #related_repos:
    #class: references # is subclass of list
    #display: [desktop, mobile] # [desktop, mobile]
    #header:
      #icon: fab fa-github
      #title: 源码链接

  # You can add your own widget here or 'blog/source/_data/widget.yml'
  # class: text, list, grid, qrcode, page, ... see more at https://volantis.js.org/



footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [social, copyright, info]
  social:
    - icon: fas fa-rss
      url: /atom.xml
    - icon: fas fa-envelope
      url: mailto:flexiston@163.com
    - icon: fab fa-github
      url: https://github.com/Flexiston
  copyright: '[Copyright © 2020 Flexiston](https://www.flexiston.com)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'


############################### Plugins ###############################
plugins:
  # npm i --save hexo-wordcount
  wordcount: true

  # Slide Background
  backstretch:
    enable: true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 20000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/41F215B9-261F-48B4-80B5-4E86E165259E.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/35F12181-F0E9-45BD-B134-37E4B4A660CF.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/00E0F0ED-9F1C-407A-9AA6-545649D919F4.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B951AE18-D431-417F-B3FE-A382403FF21B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/AEB33F9D-7294-4CF1-B8C5-3020748A9D45.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/2884F904-F1F3-479E-AE27-5EBC291B63B0.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/10A0FCE5-36A1-4AD0-8CF0-019259A89E03.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/250662D4-5A21-4AAA-BB63-CD25CF97CFF1.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/298468D7-E388-44A8-8CC5-8213BDC33CED.jpeg



############################### Comments ###############################
comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: valine # valine, minivaline, disqus, gitalk, livere
  valine:
    appId: **************** # your appId
    appKey: **************** # your appKey
    js: https://cdn.jsdelivr.net/npm/valine@latest/dist/Valine.min.js
    path: # All pages use the same path (share the same comments data)
    meta: nick,mail,link # valine comment header info
    requiredFields: ['nick','mail']
    enableQQ: true # Unstable avatar link
    placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
    avatar: mp # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    visitor: false
    mathJax: false
```

## Other Information 
Chrome, Windows 10
