### ISSUE TITLE
github和gitee同时部署时，搜索后的页面跳转问题

### ISSUE THREAD

**Issue by wongqingbin** [volantis-x/hexo-theme-volantis#269]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 
根目录下的_config.yml中设置url: https://xxxxxx.github.io  
之后同时部署到github和gitee时，在gitee部署的页面中点击搜索结果中的连接后，跳转到gitee了  
有没有分别设置跳转的方法？

### Node.js and NPM Information

```
➜  blog git:(master) node -v && npm -v
v12.16.3
6.14.4
```

### Package dependencies Information

```
➜  blog git:(master) ✗ npm ls --depth 0          
hexo-site@0.0.0 /Users/wangqingbin/blog
├── hexo@4.2.0
├── hexo-all-minifier@0.5.3
├── hexo-autonofollow@1.0.1
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-json-content@4.2.3
├── hexo-generator-search@2.4.0
├── hexo-generator-seo-friendly-sitemap@0.0.25
├── hexo-generator-tag@1.0.0
├── hexo-helper-qrcode@1.0.2
├── hexo-lazyload-image@1.0.8
├── hexo-related-popular-posts@4.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
└── hexo-wordcount@6.0.1


```

### Hexo Configuration

```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wongqingbin.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

```

### Volantis Configuration

```yml
############################### Search ###############################
# To use hexo search, you need to install the following plugins:
# npm i -S hexo-generator-search hexo-generator-json-content
search:
  enable: true
  service: hexo # hexo, google, algolia, azure, baidu
  js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.6.4/js/search.js
  google:
    apiKey:
    engineId:
  algolia:
    applicationID:
    apiKey:
    indexName:
  azure:
    serviceName:
    indexName:
    queryKey:
  baidu:
    apiId:
```
