### ISSUE TITLE
无法使用自定义字体来显示网页

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#279]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 
您好，我在主题文件的_config文件中使用了自定义字体，网页却无法以我指定的字体显示
请问我应该如何修改呢，求指教

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml
 fontfamily:
    logofont:
      fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Varela Round'
      url: https://cdn.jsdelivr.net/gh/lan-shanguiyao/cdn-blog/fonts/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: '"Microsoft YaHei","Source Han Serif CN"'
      name: 'Source Han Serif CN'
      url: https://cdn.jsdelivr.net/gh/lan-shanguiyao/cdn-blog/fonts/SourceHanSerif/SourceHanSerifCN-Regular.otf
      weight: normal
      style: normal
      offset: 0.1rem # Correct baseline for zh-CN
    codefont:
      fontfamily: '"Cascadia Code"'
      name: 'Cascadia Code'
      url: https://cdn.jsdelivr.net/gh/lan-shanguiyao/cdn-blog/fonts/Cascadia.ttf
      weight: normal
      style: normal
```

**Comment by xaoxuu** [comment]
改成这样试试：
```yaml
fontfamily:
    logofont:
      fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Varela Round'
      url: https://cdn.jsdelivr.net/gh/lan-shanguiyao/cdn-blog/fonts/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: '"Source Han Serif CN", "Microsoft YaHei"'
      name: 'Source Han Serif CN'
      url: https://cdn.jsdelivr.net/gh/lan-shanguiyao/cdn-blog/fonts/SourceHanSerif/SourceHanSerifCN-Regular.otf
      weight: normal
      style: normal
      offset: 0.1rem # Correct baseline for zh-CN
    codefont:
      fontfamily: '"Cascadia Code"'
      name: 'Cascadia Code'
      url: https://cdn.jsdelivr.net/gh/lan-shanguiyao/cdn-blog/fonts/Cascadia.ttf
      weight: normal
      style: normal
```
