### ISSUE TITLE
有一种更快的使用highlight.js的方案

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#281]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

在hexo根目录的_config.yml中开启hljs, 然后全局导入:

```yml
import:
  link:
  - '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.2/styles/atom-one-light.min.css">'
```
主题啥都不改, 大功告成(可以见我的博客, 我换成了Atom One Light主题)
