### ISSUE TITLE
侧边栏作者处出现抖动效果

### ISSUE THREAD

**Issue by penndu** [volantis-x/hexo-theme-volantis#321]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载[文档源码](https://github.com/xaoxuu/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x] 我已完成上述操作，结果是：__依然出现这个问题__

### 第三步

- [x] 我已经将主题升级到最新版本。

## 问题描述

使用谷歌浏览器访问页面时，侧边栏作者处出现抖动效果。

### 复现地址：

https://dusays.com

### 截图：

![](https://7bu.top/2020/05/23/60ec992aff506.gif)

### 浏览器、操作系统

Chrome
Win10

### 主题配置文件

```yml
blogger:
    class: blogger
    display: [desktop, mobile] # [desktop, mobile]
    avatar: https://cdn.dusays.com/avatar.png
    shape: rectangle # circle, rectangle
    url: /about/
    title: Teacher Du
    subtitle:
    jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
    social: true

```
