### ISSUE TITLE
本地无法加载/tags页面

### ISSUE THREAD

**Issue by FRTI64** [volantis-x/hexo-theme-volantis#326]
## 自检报告

分类：使用遇到问题（主题文件 ejs、js、css、第三方插件等有修改）

### 第一步 

查看未经修改的主题是否也存在此问题：

- A. 未经修改的主题也存在此问题，请使用 issue 模板「帮助流程A. 使用遇到问题（主题未经修改）」。
- B. 未经修改的主题不存在此问题，在 git 历史中新建分支还原修改，直至找到出问题的地方。

- [x] 我已完成上述操作，结果是：B

### 第二步

这部分内容是否与第三方插件有关？

- A. 是主题文档中提到过的第三方插件（意味着有主动兼容），请在问题描述中描述清楚。
- B. 是主题文档中没有提到过的第三方插件，可能存在没有兼容的情况，请使用 issue 模板「提交一个建议」。

## 问题描述

魔改了主题配置文件, 注释掉了一些组件, 然后我的tags页面就再也没有打开过

### 站点配置文件

```yml

```

### 主题配置文件

```yml
############################### Style ###############################
style:
  font_smoothing: false # font-smoothing for webkit
  max_width: 1080px # Sum of body width and sidebar width (This limit will be exceeded when the device width is greater than 2000px, reaching 75% of the total width)
  scrollbar:
    size: 4px
    border: 2px
    color: '#2196f3'
    hover: '#ff5722'
  navbar:
    height: 64px
    width: auto # auto, max
    effect: [shadow, blur] # [shadow, floatable, blur]
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
    highlight:
      language: true # show language of codeblock
      copy_btn: true
    text_align: # left, right, justify, center
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
    note: # style for default note: {% note text %}
      icon: '\f054'
      color: ''
    checkbox:
      enable: true # enable for user
      color: '' # color for default checkbox
  gap:
    h2: 48px # Spacing above H2 (only px unit)
    h3: 24px # Spacing above H3 (only px unit)
    h4: 16px # Spacing above H4 (only px unit)
    paragraph: 1rem # Paragraph spacing between paragraphs
    row: .5rem # Paragraph spacing between other elements
    line_height: 1.65 # normal, 1.5, 1.75, 2 ...
  border_radius:
    card: 8px
    codeblock: 4px
    searchbar: 8px
    button: 4px
  fontsize:
    root: 16px
    h1: 1.625rem
    h2: 1.375rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    body: 1rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .75rem
  fontfamily:
    logofont:
      fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial, Consolas'
      name: 'Consolab'
      url: /file/consolab.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'UbuntuMono, "PingFang SC", "Microsoft YaHei", Helvetica, Arial, Consolas'
      name: 'Consola'
      url: /file/consola.ttf
      weight: normal
      style: normal
      offset: 0.1rem # Correct baseline for zh-CN
    codefont:
      fontfamily: 'Menlo, UbuntuMono, Monaco, Consolas'
      name: 'Consola'
      url: /file/consola.ttf
      weight: normal
      style: normal
  # color:
  #   site: '#121212' # Website background color
  #   site_inner: '#fff' # Text color inside the website background
  #   site_footer: '#666' # Footer text color inside the website background
  #   card: '#444' # Card background color
  #   text: '#fff' # The color of the text on the card.
  #   theme: '#2196f3' # Main color
  #   link: '#1BCDFC' # Link color
  #   hover: '#ff5722' # Link highlight color
  #   inner: '#333' # Text color inside the button
  #   block: '#555' # Block color
  #   inlinecode: '#555' # Inline code color
  #   codeblock: '#555' # Codeblock color
  #   p: '#ccc' # Paragraph color




############################### Layout ###############################
cover:
  scheme: docs # docs, blog
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  logo: # https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/256/google_logo.png
  title: THE-NAMELESS-SPECTRE
  subtitle: 'GHOST'
  search: # search bar placeholder
  features:
    - name: 博客
      icon: fas fa-rss
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 关于
      icon: fas fa-info-circle
      url: about/


# Navigation Bar
navbar:
  logo: # choose [img] or [icon + title]
    img:
    icon: /file/icon.png
    title: THE-NAMELESS-SPECTRE
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
    - name: 博客
      icon: fas fa-rss
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
  search: Search...   # Search bar placeholder



layout:
  # The following can be written in `blog/source/_data/layout.yml`
  # 文章列表 (主页, 自定义的列表) 布局
  on_list:
    # 列表中每一篇文章的meta信息
    meta: [title, author, category, date, top]
    # 列表类页面的侧边栏
    sidebar: [blogger, category]
    # read more button
    readmore: 阅读全文 <i class="fas fa-chevron-right"></i>
  # 页面布局
  on_page:
    # 文章页面主体元素, 你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息, 文章中没有配置则按照这里的配置来显示, 设置为false则不显示
    # 其中, title只在header中有效, music和thumbnail无需在这里设置, 文章中有则显示
    # 如果tags放置在meta.header中, 那么在post列表中不显示 (因为卡片下方已经有了) 
    meta:
      header: [title, author, category, date, top]
      footer: [updated, tags]
    # 文章页面的侧边栏
    sidebar: [toc]
  # 文章布局, 参数继承自 on_page
  on_post:
    # 文章页脚, 自动在每一篇文章末尾添加
    article_footer: [references, copyright]
  # 其他的页面布局暂时等于 on_list


# meta library
meta:
  # 文章标题
  title: # 暂无配置
  # 默认文章作者 (可在front-matter中覆盖) 
  author:
    avatar: /file/avatar.png
    name: THE-NAMELESS-SPECTRE
    url: /
  # 文章创建日期
  date:
    icon: fas fa-calendar-alt
    title: '发布于: '
    format: 'x' # 日期格式 http://momentjs.com/docs/
  # 文章更新日期
  updated:
    icon: fas fa-edit
    title: '更新于: '
    format: 'x' # 日期格式 http://momentjs.com/docs/
  # 文章分类
  category:
    icon: fas fa-folder-open
  # 文章置顶
  top:
    icon: fas fa-angle-double-up
  # 文章浏览计数
  counter:
  #   icon: fas fa-eye
  # 文章字数和阅读时长
  wordcount:
  #   icon_wordcount: fas fa-keyboard
  #   icon_duration: fas fa-hourglass-half
  # 文章标签
  tags:
    icon: fas fa-hashtag
  # 分享
  share:
  #   - id: qq
  #     img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qq.png
  #   - id: qzone
  #     img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/qzone.png
  #   - id: weibo
  #     img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/weibo.png
  #   # - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
  #   #   img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/wechat.png
  #   # - id: telegram
  #   #   img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/telegram.png
  # 链接
  btns:
  #   edit:
  #     icon: fas fa-edit
  #     title: 在GitHub上编辑此页
  #     color: '#888'
  #   repo: # 源码链接
  #     icon: fas fa-file-code
  #     title: 源码
  #     color: '#508EF2'
  #   bug: # BUG反馈链接
  #     icon: fas fa-bug
  #     title: BUG
  #     color: '#FE5F58'
  #   doubt: # 疑问链接
  #     icon: fas fa-question-circle
  #     title: 疑问
  #     color: '#FFBD2B'
  #   idea: # 建议链接
  #     icon: fas fa-lightbulb
  #     title: 建议
  #     color: '#3DC550'
  #   faq: # FAQ链接
  #     icon: fas fa-comments
  #     title: FAQ
  #     color: '#29B1C9'
  #   feedback: # 反馈链接
  #     icon: fas fa-comment-dots
  #     title: 反馈
  #     color: '#1BCDFC'

# widget library
widget:
  # The following can be written in `blog/source/_data/widget.yml`
  # ---------------------------------------
  # blogger info widget
  blogger:
    class: blogger
    display: [desktop, mobile] # [desktop, mobile]
    avatar: /file/avatar.png
    shape: rectangle # circle, rectangle
    url: /about/
    title: THE-NAMELESS-SPECTRE
    subtitle: GHOST
    jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
    social: true
  # ---------------------------------------
  # toc widget (valid only in articles)
  toc:
    class: toc
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-list
      title: 本文目录
    list_number: false
    min_depth: 2
    max_depth: 5
  # ---------------------------------------
  # category widget
  category:
    class: category
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-folder-open
      title: 文章分类
      url: /blog/categories/
  # ---------------------------------------
  # tagcloud widget
  tagcloud:
  #   class: tagcloud
  #   display: [desktop, mobile] # [desktop, mobile]
  #   header:
  #     icon: fas fa-tags
  #     title: 热门标签
  #     url: /blog/tags/
  #   min_font: 14
  #   max_font: 24
  #   color: true
  #   start_color: '#999'
  #   end_color: '#555'
  # ---------------------------------------
  # related posts widget
  related_posts:
  #   class: related_posts # npm i -S hexo-related-popular-posts
  #   display: [desktop, mobile] # [desktop, mobile]
  #   header:
  #     icon: fas fa-bookmark
  #     title: 相关文章
  #   max_count: 5
  # ---------------------------------------
  # copyright widget (valid only in articles)
  copyright:
    class: copyright
    display: [desktop, mobile] # [desktop, mobile]
    blockquote: true
    permalink: '本文永久链接是: '
    content:
      - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
      - permalink
  # ---------------------------------------
  # qrcode widget
  donate:
  #   class: qrcode
  #   display: [desktop, mobile] # [desktop, mobile]
  #   height: 64px  # Automatic height if not set
  #   fancybox: true
  #   images:
  #     - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
  #     - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/qrcode/wiki_volantis.png
  # ---------------------------------------
  # references widget
  references:
  #   class: references # is subclass of list
  #   display: [desktop, mobile] # [desktop, mobile]
  #   header:
  #     icon: fas fa-quote-left
  #     title: 参考资料
  # related_repos:
  #   class: references # is subclass of list
  #   display: [desktop, mobile] # [desktop, mobile]
  #   header:
  #     icon: fab fa-github
  #     title: 源码链接

  # You can add your own widget here or 'blog/source/_data/widget.yml'
  # class: text, list, grid, qrcode, page, ... see more at https://volantis.js.org/



footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, info, copyright]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:the-nameless-spectre@outlook.com
    - icon: fab fa-github
      url: https://github.com/THE-NAMELESS-SPECTRE
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=3267142740
  copyright: '[Copyright © 2019-2020 THE-NAMELESS-SPECTRE](/)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'


############################### SEO ###############################
seo:
  # When there are no keywords in the article's front-matter, use tags as keywords.
  use_tags_as_keywords: true
  # When there is no description in the article's front-matter, use excerpt as the description.
  use_excerpt_as_description: false
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
    # robots can be written in front-matter


############################### Plugins ###############################
plugins:
  ######## Plugins to improve loading speed:
  # Preload (The menu's url must end with ‘/’)
  # instant_page: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/instant_page.js

  ######## Plugins to optimize the experience:
  # highlight.js
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@9.18.1/styles/solarized-light.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    js: https://cdn.jsdelivr.net/npm/scrollreveal@4.0.6/dist/scrollreveal.min.js
    distance: 8px
    duration: 800 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

  # Codeblock Copy Button
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  ######## Plugins for SEO:
  # Traffic statistics (very slow loading)
  # busuanzi: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js

  # npm i --save hexo-wordcount
  # wordcount: #true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

  # Typing Effects
  comment_typing: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2/js/comment_typing.js

  # Slide Background
  backstretch:
    enable: true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 20000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - /file/wallpaper.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/BBC19066-E176-47C2-9D22-48C81EE5DF6B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B18FCBB3-67FD-48CC-B4F3-457BA145F17A.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/35F12181-F0E9-45BD-B134-37E4B4A660CF.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/00E0F0ED-9F1C-407A-9AA6-545649D919F4.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/67239FBB-E15D-4F4F-8EE8-0F1C9F3C4E7C.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/B951AE18-D431-417F-B3FE-A382403FF21B.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/AEB33F9D-7294-4CF1-B8C5-3020748A9D45.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/abstract/2884F904-F1F3-479E-AE27-5EBC291B63B0.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/10A0FCE5-36A1-4AD0-8CF0-019259A89E03.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/250662D4-5A21-4AAA-BB63-CD25CF97CFF1.jpeg
      # - https://cdn.jsdelivr.net/gh/xaoxuu/cdn-wallpaper/landscape/298468D7-E388-44A8-8CC5-8213BDC33CED.jpeg

  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: true
    js:
      - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
      - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 4930734283    # song id / playlist id / album id / search keyword
    # Optional
    fixed: false      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 340px # list max height
    list_folded: true




############################### Comments ###############################
comments:
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: gitalk # valine, minivaline, disqus, gitalk, livere
  # # Valine
  # # https://valine.js.org/
  # valine:
  #   appId: dogUA2FSKGTo029M1SEwGROT-MdYXbMMI # your appId
  #   appKey: u0NdtQ8nvHoMdJPSYqm1LRxE # your appKey
  #   js: https://cdn.jsdelivr.net/npm/valine@1.4/dist/Valine.min.js
  #   path: # All pages use the same path (share the same comments data)
  #   meta: nick,mail,link # valine comment header info
  #   requiredFields: ['nick','mail']
  #   enableQQ: true # Unstable avatar link
  #   placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  #   avatar: robohash # gravatar style https://valine.js.org/avatar
  #   pageSize: 10 # comment list page size
  #   lang: zh-cn
  #   highlight: true
  #   visitor: true
  #   mathJax: false
  # # MiniValine
  # # https://github.com/MiniValine/MiniValine
  # minivaline:
  #   appId: # your appId
  #   appKey: # your appKey
  #   js: https://cdn.jsdelivr.net/npm/minivaline@2/dist/MiniValine.min.js
  #   mode: xCss # DesertsP or xCss
  #   placeholder: 快来评论吧~ # Comment box placeholder
  #   path: # All pages use the same path (share the same comments data)
  #   math: true # Support MathJax.
  #   md: true # Support Markdown.
  #   enableQQ: false # Enable QQ avatar API.
  #   NoRecordIP: false # Do not record commenter IP.
  #   visitor: true # Article reading statistics.
  #   maxNest: 6 # Sub-comment maximum nesting depth.
  #   pageSize: 6 # Pagination size.
  #   adminEmailMd5: de8a7aa53d07e6b6bceb45c64027763d # The MD5 of Admin Email to show Admin Flag.[ Just Only DesertsP Style mode]
  #   tagMeta: # The String Array of Words to show Flag.[ Just Only xCss Style mode]
  #     - 管理员
  #     - 小伙伴
  #     - 访客
  #   master: # The MD5 String Array of master Email to show master Flag.[ Just Only xCss Style mode]
  #     - de8a7aa53d07e6b6bceb45c64027763d
  #   friends: # The MD5 String Array of friends Email to show friends Flag. [ Just Only xCss Style mode]
  #     - b5bd5d836c7a0091aa8473e79ed4c25e
  #     - adb7d1cd192658a55c0ad22a3309cecf
  #     - 3ce1e6c77b4910f1871106cb30dc62b0
  #     - cfce8dc43725cc14ffcd9fb4892d5bfc
  #   # MiniValine's display language depends on user's browser or system environment
  #   # If you want everyone visiting your site to see a uniform language, you can set a force language value
  #   # Available values: en  | zh-CN | (and many more)
  #   # More i18n info: https://github.com/MiniValine/minivaline-i18n
  #   lang:
  #   # Expression Url.
  #   # https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-customize-emoticons
  #   emoticonUrl:
  #     - https://cdn.jsdelivr.net/npm/alus@latest
  #     - https://cdn.jsdelivr.net/gh/MiniValine/qq@latest
  #     - https://cdn.jsdelivr.net/gh/MiniValine/Bilibilis@latest
  #     - https://cdn.jsdelivr.net/gh/MiniValine/tieba@latest
  #     - https://cdn.jsdelivr.net/gh/MiniValine/twemoji@latest
  #     - https://cdn.jsdelivr.net/gh/MiniValine/weibo@latest
  # # Disqus
  # # https://disqus.com
  # disqus:
  #   shortname:
  # Gitalk
  # https://gitalk.github.io/
  gitalk:
    clientID:
    clientSecret:
    repo:
    owner:
    admin: # []
  # # Vssue
  # # https://vssue.js.org/zh/
  # vssue:
  #   owner:
  #   repo:
  #   clientId:
  #   clientSecret:
  # # LiveRe
  # # https://www.livere.com
  # livere:
  #   uid:




############################### Search ###############################
# To use hexo search, you need to install the following plugins:
# npm i -S hexo-generator-search hexo-generator-json-content
search:
  enable: true
  service: hexo  # hexo, google, algolia, azure, baidu
  js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.6.5/js/search.js
  google:
    apiKey:
    engineId:
  algolia:
    applicationID:
    apiKey:
    indexName:
  azure:
    serviceName:
    indexName:
    queryKey:
  baidu:
    apiId:



############################### Theme Information ###############################
info:
  name: Volantis # This is theme's name.
  version: '2.6.6' # This is theme's version.
  docs: https://volantis.js.org/ # This is theme's URL.
  cdn:
    js: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-volantis@2.6.5/js/app.js
    css:

```

#### node.js & npm

```

```

#### package.json

```

```

给一下hexo cl, hexo g, hexo s的输出
```

GHOST@DESKTOP-DOAQJ8U MINGW64 /c/blog
$ hexo cl
(node:4684) Warning: Accessing non-existent property 'lineno' of module exports
inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4684) Warning: Accessing non-existent property 'column' of module exports
inside circular dependency
(node:4684) Warning: Accessing non-existent property 'filename' of module export
s inside circular dependency
(node:4684) Warning: Accessing non-existent property 'lineno' of module exports
inside circular dependency
(node:4684) Warning: Accessing non-existent property 'column' of module exports
inside circular dependency
(node:4684) Warning: Accessing non-existent property 'filename' of module export
s inside circular dependency
INFO  Deleted database.
INFO  Deleted public folder.

GHOST@DESKTOP-DOAQJ8U MINGW64 /c/blog
$ hexo g
(node:8912) Warning: Accessing non-existent property 'lineno' of module exports
inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8912) Warning: Accessing non-existent property 'column' of module exports
inside circular dependency
(node:8912) Warning: Accessing non-existent property 'filename' of module export
s inside circular dependency
(node:8912) Warning: Accessing non-existent property 'lineno' of module exports
inside circular dependency
(node:8912) Warning: Accessing non-existent property 'column' of module exports
inside circular dependency
(node:8912) Warning: Accessing non-existent property 'filename' of module export
s inside circular dependency
INFO  Start processing
INFO  Files loaded in 361 ms
ERROR C:\blog\themes\volantis\layout\tag.ejs:15
    13|               <div class="archive-item all-tags">
    14|                 <% let tc = theme.widget.tagcloud; %>
 >> 15|                 <%- tagcloud(site.tags, {
    16|                     min_font: tc.min_font,
    17|                     max_font: tc.max_font,
    18|                     color: tc.color,

Cannot read property 'min_font' of null
TypeError: C:\blog\themes\volantis\layout\tag.ejs:15
    13|               <div class="archive-item all-tags">
    14|                 <% let tc = theme.widget.tagcloud; %>
 >> 15|                 <%- tagcloud(site.tags, {
    16|                     min_font: tc.min_font,
    17|                     max_font: tc.max_font,
    18|                     color: tc.color,

Cannot read property 'min_font' of null
    at eval (C:\blog\themes\volantis\layout\tag.ejs:38:34)
    at tag (C:\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (C:\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (C:\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at C:\blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (C:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:475:10)
    at resume_ (_stream_readable.js:962:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
ERROR C:\blog\themes\volantis\layout\post.ejs:3
    1| <%- partial('_pre') %>
    2| <div class='l_main<%- page.sidebar == false ? ' no_sidebar' : '' %>'>
 >> 3|   <%- partial('_partial/article', {post: page, index: false}) %>
    4| </div>
    5| <%- partial('_partial/side') %>
    6| <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>

C:\blog\themes\volantis\layout\_partial\article.ejs:17
    15|                 <%- partial('../_widget/load', {widgets: page.meta.artic
le_footer, where: 'article'}) %>
    16|               <% } else { %>
 >> 17|                 <%- partial('../_widget/load', {widgets: theme.layout.on
_post.article_footer, where: 'article'}) %>
    18|               <% } %>
    19|             </div>
    20|           <% } %>

C:\blog\themes\volantis\layout\_widget\load.ejs:3
    1| <% (widgets||[]).forEach(function(widget){ %>
    2|   <% if (theme.widget && (widget in theme.widget)){ %>
 >> 3|     <% let w = theme.widget[widget]; w.id = widget; %>
    4|     <%- partial(w.class, {item: w, where: where}) %>
    5|   <% } else if (site.data.widget && (widget in site.data.widget)){ %>
    6|     <% let w = site.data.widget[widget]; w.id = widget; %>

Cannot set property 'id' of null
TypeError: C:\blog\themes\volantis\layout\post.ejs:3
    1| <%- partial('_pre') %>
    2| <div class='l_main<%- page.sidebar == false ? ' no_sidebar' : '' %>'>
 >> 3|   <%- partial('_partial/article', {post: page, index: false}) %>
    4| </div>
    5| <%- partial('_partial/side') %>
    6| <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>

C:\blog\themes\volantis\layout\_partial\article.ejs:17
    15|                 <%- partial('../_widget/load', {widgets: page.meta.artic
le_footer, where: 'article'}) %>
    16|               <% } else { %>
 >> 17|                 <%- partial('../_widget/load', {widgets: theme.layout.on
_post.article_footer, where: 'article'}) %>
    18|               <% } %>
    19|             </div>
    20|           <% } %>

C:\blog\themes\volantis\layout\_widget\load.ejs:3
    1| <% (widgets||[]).forEach(function(widget){ %>
    2|   <% if (theme.widget && (widget in theme.widget)){ %>
 >> 3|     <% let w = theme.widget[widget]; w.id = widget; %>
    4|     <%- partial(w.class, {item: w, where: where}) %>
    5|   <% } else if (site.data.widget && (widget in site.data.widget)){ %>
    6|     <% let w = site.data.widget[widget]; w.id = widget; %>

Cannot set property 'id' of null
    at eval (C:\blog\themes\volantis\layout\_widget\load.ejs:16:43)
    at Array.forEach (<anonymous>)
    at eval (C:\blog\themes\volantis\layout\_widget\load.ejs:10:22)
    at load (C:\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync (C:\blog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (C:\blog\node_modules\hexo\lib\theme\view.js:60:23
)
    at Object.partial (C:\blog\node_modules\hexo\lib\plugins\helper\partial.js:3
4:15)
    at eval (C:\blog\themes\volantis\layout\_partial\article.ejs:53:17)
    at Array.forEach (<anonymous>)
    at eval (C:\blog\themes\volantis\layout\_partial\article.ejs:13:17)
    at article (C:\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiledSync (C:\blog\node_modules\hexo\lib\theme\view.js:132:22)
    at viewFn.View.renderSync (C:\blog\node_modules\hexo\lib\theme\view.js:60:23
)
    at Object.partial (C:\blog\node_modules\hexo\lib\plugins\helper\partial.js:3
4:15)
    at eval (C:\blog\themes\volantis\layout\post.ejs:16:17)
    at post (C:\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (C:\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (C:\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at C:\blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (C:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\blog\node_modules\hexo\lib\hexo\router.js:126:3)
INFO  Generated: search.xml
INFO  Generated: content.json
(node:8912) Warning: Accessing non-existent property 'lineno' of module exports
inside circular dependency
(node:8912) Warning: Accessing non-existent property 'column' of module exports
inside circular dependency
(node:8912) Warning: Accessing non-existent property 'filename' of module export
s inside circular dependency
(node:8912) Warning: Accessing non-existent property 'lineno' of module exports
inside circular dependency
(node:8912) Warning: Accessing non-existent property 'column' of module exports
inside circular dependency
(node:8912) Warning: Accessing non-existent property 'filename' of module export
s inside circular dependency
INFO  Generated: index.html
INFO  Generated: tags/index.html
INFO  Generated: post/Hello-World.html
INFO  Generated: about/index.html
INFO  Generated: categories/index.html
INFO  Generated: archives/index.html
INFO  Generated: friends/index.html
INFO  Generated: img/algolia.svg
INFO  Generated: fonts/Monaco.ttf
INFO  Generated: archives/2020/05/index.html
INFO  Generated: js/app.js
INFO  Generated: css/style.css
INFO  Generated: fonts/Skranji-Regular.ttf
INFO  Generated: img/baidu.svg
INFO  Generated: archives/2020/index.html
INFO  Generated: img/azure.svg
INFO  Generated: js/valine.js
INFO  Generated: js/search.js
INFO  Generated: fonts/Ubuntu-Regular.ttf
INFO  Generated: file/consolab.ttf
INFO  Generated: file/consolai.ttf
INFO  Generated: file/consolaz.ttf
INFO  Generated: file/consola.ttf
INFO  Generated: file/avatar.png
INFO  Generated: file/imagine.png
INFO  Generated: file/icon.png
INFO  Generated: file/logo.png
INFO  Generated: file/wallpaper.jpeg
INFO  30 files generated in 961 ms

GHOST@DESKTOP-DOAQJ8U MINGW64 /c/blog
$ hexo s
(node:7352) Warning: Accessing non-existent property 'lineno' of module exports
inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7352) Warning: Accessing non-existent property 'column' of module exports
inside circular dependency
(node:7352) Warning: Accessing non-existent property 'filename' of module export
s inside circular dependency
(node:7352) Warning: Accessing non-existent property 'lineno' of module exports
inside circular dependency
(node:7352) Warning: Accessing non-existent property 'column' of module exports
inside circular dependency
(node:7352) Warning: Accessing non-existent property 'filename' of module export
s inside circular dependency
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
#  以下输出为试图打开tags页面后
Unhandled rejection TypeError: C:\blog\themes\volantis\layout\tag.ejs:15
    13|               <div class="archive-item all-tags">
    14|                 <% let tc = theme.widget.tagcloud; %>
 >> 15|                 <%- tagcloud(site.tags, {
    16|                     min_font: tc.min_font,
    17|                     max_font: tc.max_font,
    18|                     color: tc.color,

Cannot read property 'min_font' of null
    at eval (C:\blog\themes\volantis\layout\tag.ejs:38:34)
    at tag (C:\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (C:\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (C:\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at C:\blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (C:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:475:10)
    at resume_ (_stream_readable.js:962:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```
