### ISSUE TITLE
APlayer播放器无法调节音量

### ISSUE THREAD

**Issue by 954L** [volantis-x/hexo-theme-volantis#328]
## BUG描述

在子菜单中，新增一个 icon: fas fa-compact-disc 的“菜单”就会被渲染成一个 APlayer 播放器。

使用此功能之后，在子菜单中的播放器无法调节音量，默认配置为0.7，首次打开是正常的，但是拖动音量的时候立马归0，且无法加大音量，导致无声。只有刷新页面重新加载，才有效。

## 复现报告

分类：反馈一个明确的BUG

- [ x ] 将主题升级至最新版本。
- [ x ] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。

### 复现步骤

1. 修改配置文件
![image](https://user-images.githubusercontent.com/35250721/83737531-b540b780-a685-11ea-99bc-7bf180cd59b6.png)

2. 执行hexo命令
> hexo g -d

3. 打开网站即可复现

### 截图：

![image](https://user-images.githubusercontent.com/35250721/83737725-f933bc80-a685-11ea-81d8-aaa4e392af66.png)

### 浏览器、操作系统
win10
谷歌浏览器

### 站点配置文件

```yml

```

### 主题配置文件

```yml
# Navigation Bar
navbar:
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title:
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
#    - name: ......
#      icon: fas fa-rss
#      url: /
    - name: ............
      icon: fas fa-compact-disc
#    - name: ......
#      icon: fas fa-folder-open
#      url: categories/
#    - name: ......
#      icon: fas fa-tags
#      url: tags/
#    - name: ......
#      icon: fas fa-archive
#      url: archives/
#    - name: ......
#      icon: fas fa-link
#      url: friends/
#    - name: ......
#      icon: fas fa-info-circle
#      url: about/
  search: Search...   # Search bar placeholder

```

#### node.js & npm

```
/themes/volantis # node -v && npm -v
v12.16.3
6.14.4

```

#### package.json

```

```
