### ISSUE TITLE
代码高亮需要刷新页面才有效

### ISSUE THREAD

**Issue by zyan1226** [volantis-x/hexo-theme-volantis#365]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载[文档源码](https://github.com/volantis-x/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x] 我已完成上述操作，结果是：无作用

### 第三步

- [x] 我已经将主题升级到最新版本。3.0-beta1

## 问题描述

第一次进入文章页面，代码块不会高亮，需要手动刷新一下才正常。

### 复现地址：

示例地址: 
https://yzweb.gitee.io/tags/Java-%E5%B0%8F%E7%9F%A5%E8%AF%86/

### 截图：

第一此进入

![图1](https://user-images.githubusercontent.com/45474597/87371515-242ffb00-c5b8-11ea-9c40-1c063debc585.png)

刷新后

![图2](https://user-images.githubusercontent.com/45474597/87371562-3dd14280-c5b8-11ea-89b4-9aaebb22d7fd.png)

通过主页列表或其他位置重新进入，与 图1 效果一致，没有高亮。

### 浏览器、操作系统
Google Chrome、win 10
### 站点配置文件

```yml
highlight:
  enable: false
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: true
```
### 主题配置文件

```yml
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@9.18.1/styles/darcula.min.css
```

#### node.js & npm

```

```

#### package.json

```

```
