### ISSUE TITLE
可以增加自己定义的SOCIAL ICON吗

### ISSUE THREAD

**Issue by weikunhan** [volantis-x/hexo-theme-volantis#371]
## 自检报告

- [ x] 我已阅读主题文档，确认不存在此功能。
- [ x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

我想再自己定义的SOCIAL ICON
  footer:
    layout: [aplayer, social, info, copyright]
    social:
      - icon: https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg
        url: xxxx

可以吗？

我找到对应的代码如下，不知道怎么改
```
    <% layout.forEach(function(item){ %>
      <% if (item == 'social') { %>
        <br>
        <div class="social-wrapper">
          <% (theme.footer.social||[]).forEach(function(value){ %>
            <% if (value.url && value.icon) { %>
              <a href="<%= url_for(value.url) %>"
                class="social <%- value.icon %> flat-btn"
                target="_blank"
                rel="external nofollow noopener noreferrer">
              </a>
              <a 
                href="https://cdn.jsdelivr.net/gh/weikunhan/cdn-documents@latest/images/new_weikun_han_web_1.png" 
                    type="image/x-icon" 
                    target="_blank"
                    rel="external nofollow noopener noreferrer"></a>


            <%}%>
            
          <%})%>

        </div>
      <% } else if (item == 'aplayer') { %>
```

**Comment by weikunhan** [comment]
+1

**Comment by inkss** [comment]
主题原生提供了自定义配置：[查看文档](https://volantis.js.org/v3/theme-settings/#%E8%AE%BE%E7%BD%AE%E7%BD%91%E7%AB%99%E9%A1%B5%E8%84%9A)，修改 social 下的内容，icon 或者 url 之类的。

```yml
footer:
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:me@xaoxuu.com
    - icon: fab fa-github
      url: https://github.com/xaoxuu
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=63035382
```
