### ISSUE TITLE
pjax跳转屏蔽的url地址不生效

### ISSUE THREAD

**Issue by penndu** [volantis-x/hexo-theme-volantis#376]
## BUG描述

设置了pjax跳转屏蔽的url地址，但跳转时，仍然是pjax。

## 复现报告

分类：反馈一个明确的BUG

- [x] 将主题升级至最新版本。
- [x] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [x] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

1. 进网站dusays.com；
2. 点击导航栏的说说；
3. f12会看到错误，因为pjax跳转导致的。

### 复现地址：

https://dusays.com

### 截图：

![Snipaste_2020-07-18_22-25-31.jpg](https://7bu.top/2020/07/18/6965cc2d7332f.jpg)

### 浏览器、操作系统

opera
win10

### 站点配置文件

```yml
没有修改
```

### 主题配置文件

```yml
  pjax:
    enable: true
    timeout: 5000        # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
    cacheBust: false     # When set to true, Pjax appends a timestamp  to skip the browser cache.
    animation: nprogress # nprogress, circle
    banUrl:              # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      - '/shuoshuo/index.html'
```

#### node.js & npm

```

```

#### package.json

```

```

**Comment by inkss** [comment]
判断的时候使用 == 匹配的，你那边从导航栏过去的链接是 /shuoshuo/

**Comment by inkss** [comment]
此外，也可以写多个
```
banurl:
  - balabal
  - dididada
```

**Comment by Colsrch** [comment]
``` yml
    pjax:
      enable: true
      timeout: 5000        # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
      cacheBust: false     # When set to true, Pjax appends a timestamp  to skip the browser cache.
      animation: nprogress # nprogress, circle
      banUrl:              # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
        - '/Creator-said/'
```
