### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by lxiaocode11** [volantis-x/hexo-theme-volantis#379]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载 [文档源码](https://github.com/volantis-x/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x] 我已完成上述操作，结果是：____

### 第三步

- [x] 我已经将主题升级到最新版本。

## 问题描述
我想问一下，代码块如何达到文档中的效果？鼠标悬停在代码块中显示高亮，否则不显示。

**Comment by xaoxuu** [comment]
![image](https://user-images.githubusercontent.com/16400144/88033876-7c479e00-cb72-11ea-9022-e428d6cee1e8.png)

**Comment by lxiaocode11** [comment]
我的版本是：
hexo 4.2.0 
Volantis 3.0-beta1

我在文档中没有看到相关配置的说明，自己尝试也没能达到效果。不知道该如何配置？

下面是我根据 主题文档的源码（volantis-x/hexo-theme-volantis） 中的配置来我的博客，并没有达到我想要的效果。不知道我是否遗漏其他配置或者配置出错了？

**博客配置文件**
```yml
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '  '
  wrap: true
  hljs: false
```

**主题配置**
```yml
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@9.18.1/styles/solarized-light.css
```
