### ISSUE TITLE
分类标签页渲染

### ISSUE THREAD

**Issue by zryyyy** [volantis-x/hexo-theme-volantis#443]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

A. 能正常运行，代表主题和当前环境配置都没有问题。
B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

- [A] 测试结果是：A or B

## 问题描述
在使用'hexo new page categories'命令创建完分类页后
INFO  Validating config
INFO  Created: ~\Blog\hexo\source\categories\index.md
提示创建成功，修改index.md的font-matter
---
title: categories
date: 2020-08-15 15:32:54
type: "categories"
comments: false
---
执行'hexo s'
但是此时若在浏览器中输入http://localhost:4000/blog/tags/，浏览器提示Cannot GET /blog/tags/
只能访问http://localhost:4000/categories/，但是页面为空白文章
首页右侧可以正常加载分类，如点击“代码分类”，访问的网址为http://localhost:4000/categories/代码/，可以正常显示“代码”分类下的文章，但是点击文章分类访问的网址为http://localhost:4000/blog/categories/

### 截图

<details><summary>相关截图</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
############################### Style ###############################
style:
  cursor:
    enable: true
    text: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/text.png
    pointer: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/pointer.png
    default: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/left_ptr.png
    not-allowed: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/circle.png
    zoom-out: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/zoom-out.png
    zoom-in: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/zoom-in.png
    grab: https://cdn.jsdelivr.net/gh/inkss/common@master/cursor/openhand.png
  font_smoothing: true # font-smoothing for webkit
  max_width: 1080px # Sum of body width and sidebar width (This limit will be exceeded when the device width is greater than 2000px, reaching 75% of the total width)
  scrollbar:
    size: 4px
    border: 2px
    color: '#2196f3'
    hover: '#ff5722'
  navbar:
    height: 64px
    width: auto # auto, max
    effect: [shadow, blur] # [shadow, floatable, blur]
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
    highlight:
      language: true # show language of codeblock
      copy_btn: true
      grayscale: false # Enable grayscale effect
    text_align: # left, right, justify, center
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
    note: # style for default note: {% note text %}
      icon: '\f054'
      color: ''
    checkbox:
      enable: true # enable for user
      color: '' # color for default checkbox
  gap:
    h2: 48px # Spacing above H2 (only px unit)
    h3: 24px # Spacing above H3 (only px unit)
    h4: 16px # Spacing above H4 (only px unit)
    paragraph: .6rem # Paragraph spacing between paragraphs
    row: .4rem # Paragraph spacing between other elements
    line_height: 1.65 # normal, 1.5, 1.75, 2 ...
  border_radius:
    card: 8px
    codeblock: 4px
    searchbar: 8px
    button: 4px
  fontsize:
    root: 16px
    h1: 1.625rem
    h2: 1.375rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    body: .9375rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .75rem
  fontfamily:
    logofont:
      fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Varela Round'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'UbuntuMono, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'UbuntuMono'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts/UbuntuMono/UbuntuMono-Regular.ttf
      weight: normal
      style: normal
      offset: 0.1rem # Correct baseline for zh-CN
    codefont:
      fontfamily: 'Menlo, UbuntuMono, Monaco'
      # name: 'Monaco'
      # url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts/Monaco/Monaco.ttf
      # weight: normal
      # style: normal
    note-tag:
      fontfamily: 'Font Awesome 5 Free'
  # color:
  #   site: '#21232F' # Website background color
  #   site_inner: '#fff' # Text color inside the website background
  #   site_footer: '#666' # Footer text color inside the website background
  #   card: '#444' # Card background color
  #   text: '#fff' # The color of the text on the card.
  #   # theme: '#ff9800' # Main color
  #   link: '#1BCDFC' # Link color
  #   hover: '#ff5722' # Link highlight color
  #   inner: '#333' # Text color inside the button
  #   block: '#555' # Block color
  #   codeblock: '#48371A' # Codeblock color
  #   p: '#ccc' # Paragraph color




############################### Layout ###############################
cover:
  scheme: docs # docs, blog
  layout: dock # search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  logo: /img/LOGO.png
  title: ''
  subtitle: ''
  search: A Wonderful Theme for Hexo # search bar placeholder
  features:
    #- name: 文档
    #  icon: fas fa-book
    #  url: /v3/getting-started/
    #- name: 帮助
    #  icon: fas fa-question-circle
    #  url: faqs/
    #- name: 示例
    #  icon: fas fa-play-circle
    #  url: /examples/
    #- name: 社区
    #  icon: fas fa-fan fa-spin
    #  url: /contributors/
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 友链
      icon: fas fa-link
      url: friends/



# Navigation Bar
navbar:
  logo: # choose [img] or [icon + title]
    img: /img/LOGO1.png
    icon:
    title:
  menu:
    # The following can be written in `blog/source/_data/menu.yml`
    - name: 博客
      icon: fas fa-rss
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
  search: Search...   # Search bar placeholder



layout:
  # The following can be written in `blog/source/_data/layout.yml`
  # 文章列表（主页、自定义的列表）布局
  on_list:
    # 列表中每一篇文章的meta信息
    meta: [title, author, category, date, wordcount, counter, valinecount, pin]
    # 列表类页面的侧边栏
    sidebar: [blogger, category, tagcloud, qrcode]
    # read more button
    readmore: 阅读全文 <i class="fas fa-chevron-right"></i>
  # 页面布局
  on_page:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    meta:
      header: [title, author, category, date, wordcount, pin]
      footer: [updated, tags, btns, share]
    # 文章页面的侧边栏
    sidebar: [qrcode, toc]
  # 文章布局，参数继承自 on_page
  on_post:
    # 文章页脚，自动在每一篇文章末尾添加
    article_footer: [references, related_repos, copyright, donate]
  # 其他的页面布局暂时等于 on_list


# meta library
meta:
  # 文章标题
  title: # 暂无配置
  # 默认文章作者（可在front-matter中覆盖）
  author:
    avatar: /img/monster_cat.png
    name: zry
    url: /
  # 文章创建日期
  date:
    icon: fas fa-calendar-alt
    title: '发布于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章更新日期
  updated:
    icon: fas fa-edit
    title: '更新于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章分类
  category:
    icon: fas fa-folder-open
  # 文章置顶
  pin:
    icon: fas fa-angle-double-up
  # 文章浏览计数
  counter:
    icon: fas fa-eye
  # 文章评论数量：只支持 valine
  valinecount:
    icon: fas fa-comment-dots
    desc: '' # 条评论
  # 文章字数和阅读时长
  wordcount:
    icon_wordcount: fas fa-keyboard
    icon_duration: fas fa-hourglass-half
  # 文章标签
  tags:
    icon: fas fa-hashtag
  # 分享
  share:
    - id: qq
      img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
    - id: qzone
      img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
    - id: weibo
      img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
    # - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
    #   img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/wechat.png
    # - id: telegram
    #   img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/telegram.png
  # 链接
  btns:
    edit:
      icon: fas fa-edit
      title: 在GitHub上编辑此页
      color: '#888'
    repo: # 源码链接
      icon: fas fa-file-code
      title: 源码
      color: '#508EF2'
    bug: # BUG反馈链接
      icon: fas fa-bug
      title: BUG
      color: '#FE5F58'
    doubt: # 疑问链接
      icon: fas fa-question-circle
      title: 疑问
      color: '#FFBD2B'
    idea: # 建议链接
      icon: fas fa-lightbulb
      title: 建议
      color: '#3DC550'
    faq: # FAQ链接
      icon: fas fa-comments
      title: FAQ
      color: '#29B1C9'
    feedback: # 反馈链接
      icon: fas fa-comment-dots
      title: 反馈
      color: '#1BCDFC'

# widget library
widget:
  # The following can be written in `blog/source/_data/widget.yml`
  # ---------------------------------------
  # blogger info widget
  blogger:
    class: blogger
    display: [desktop, mobile] # [desktop, mobile]
    avatar: /img/tx1.jpg
    shape: rectangle # circle, rectangle
    url: /about/
    title:
    subtitle:
    jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
    social: true
  # ---------------------------------------
  # toc widget (valid only in articles)
  toc:
    class: toc
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-list
      title: 本文目录
    list_number: false
    min_depth: 2
    max_depth: 5
  # ---------------------------------------
  # category widget
  category:
    class: category
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-folder-open
      title: 文章分类
      url: /blog/categories/
  # ---------------------------------------
  # tagcloud widget
  tagcloud:
    class: tagcloud
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-tags
      title: 热门标签
      url: /blog/tags/
    min_font: 14
    max_font: 24
    color: true
    start_color: '#999'
    end_color: '#555'
  # ---------------------------------------
  # related posts widget
  related_posts:
    class: related_posts # npm i -S hexo-related-popular-posts
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-bookmark
      title: 相关文章
    max_count: 5
  # ---------------------------------------
  # copyright widget (valid only in articles)
  copyright:
    class: copyright
    display: [desktop, mobile] # [desktop, mobile]
    blockquote: true
    permalink: '本文永久链接是：'
    content:
      - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
      - permalink
  # ---------------------------------------
  # qrcode widget
  donate:
    class: qrcode
    display: [desktop, mobile] # [desktop, mobile]
    height: 64px  # Automatic height if not set
    fancybox: true
    images:
      - /img/qqqr.png
      - /img/wxqr.png
      - /img/zfbqr.png
  # ---------------------------------------
  # references widget
  references:
    class: references # is subclass of list
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-quote-left
      title: 参考资料
  related_repos:
    class: references # is subclass of list
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fab fa-github
      title: 源码链接
  # ---------------------------------------
  # webinfo widget
  webinfo:
    class: webinfo
    display: [desktop]
    header:
      icon: fas fa-award
      title: 站点信息
    type:
      article:
        enable: true
        text: '文章数目：'
        unit: '篇'
      runtime:
        enable: true
        data: '2020/01/01'    # 填写建站日期
        text: '已运行时间：'
        unit: '天'
      wordcount:
        enable: true
        text: '本站总字数：'   # 需要启用 wordcount
        unit: '字'
      siteuv:
        enable: true
        text: '本站访客数：'   # 需要启用 busuanzi
        unit: '人'
      sitepv:
        enable: true
        text: '本站总访问量：' # 需要启用 busuanzi
        unit: '次'
      lastupd:
        enable: true
        friendlyShow: true    # 更友好的时间显示
        text: '最后活动时间：'
        unit: '日'

  # You can add your own widget here or 'blog/source/_data/widget.yml'
  # class: text, list, grid, qrcode, page, ... see more at https://volantis.js.org/



footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, copyright, br, info]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:1931860504@qq.com
    #- icon: fab fa-qq
    #  url: https://user.qzone.qq.com/1931860504
    - icon: fab fa-weibo 
      url: https://weibo.com/zryhsgj
    - icon: fab fa-github
      url: https://github.com/zryyyy
    - icon: fas fa-headphones-alt
      url: https://www.xiami.com/user/262628077
    
  # site source
  source: https://github.com/volantis-x/volantis-docs/
  # site copyright
  copyright: '[Copyright © 2020-2020 zry](/)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '**Vi Veri Veniversum Vivus Vici**'


############################### SEO ###############################
seo:
  # When there are no keywords in the article's front-matter, use tags as keywords.
  use_tags_as_keywords: true
  # When there is no description in the article's front-matter, use excerpt as the description.
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
    # robots can be written in front-matter


############################### Plugins ###############################
plugins:
  ################ required plugins ################

  # jquery
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.5/dist/jquery.min.js

  ################ optional plugins ################

  # fontawesome
  fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13/css/all.min.css
  # fontawesome animation
  fontawesome_animation: https://cdn.jsdelivr.net/gh/l-lin/font-awesome-animation/dist/font-awesome-animation.min.css
  # fancybox
  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css


  ######## Plugins to improve loading speed:
  # Preload (The menu's url must end with ‘/’)
  instant_page: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@2/js/instant_page.js

  ######## Plugins to optimize the experience:
  # highlight.js
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@9.18.1/styles/solarized-light.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    js: https://cdn.jsdelivr.net/npm/scrollreveal@4.0.6/dist/scrollreveal.min.js
    distance: 32px
    duration: 800 # ms
    interval: 20 # ms
    scale: 1 # 0.1~1

  # Codeblock Copy Button
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  ######## Plugins for SEO:
  # Traffic statistics (very slow loading)
  busuanzi: https://cdn.jsdelivr.net/gh/volantis-x/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js

  # npm i --save hexo-wordcount
  wordcount: true #true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

  # Typing Effects
  comment_typing: #https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@2/js/comment_typing.js

  # Slide Background
  backstretch:
    enable: true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 20000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/001.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/002.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/003.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/004.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/005.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/006.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/012.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/016.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/019.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/025.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/033.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/034.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/035.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/038.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/039.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/042.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/046.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/051.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/052.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/054.jpg
      - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/056.jpg

  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: true
    js:
      - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
      - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
      - js/aplayer.js
    # Required
    server: xiami   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 1238995135    # song id / playlist id / album id / search keyword
    # Optional
    fixed: false      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 320px # list max height
    list_folded: true
  pjax:
    enable: true
    timeout: 5000        # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
    cacheBust: false     # When set to true, Pjax appends a timestamp  to skip the browser cache.
    animation: nprogress # nprogress, circle
    banUrl:              # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      # - '/about/index.html'

  # Artitalk https://artitalk.js.org
  # 配置过程请参考：https://artitalk.js.org/doc.html
  # 除appID和appKEY外均为选填项
  Artitalk:
    enable: false # true为开启，false为关闭
    appID: ogP8qj3veMh0LFpFWMPOyF0X-MdYXbMMI # your appID
    appKEY: nHXLd3N3Jgh460t2iRQKWAtr # your appKEY
    # severurl:  #leancloud绑定的安全域名，使用国际版的话不需要填写
    # slanguage: # 语言设置，zh为汉语，en为英语，es为西班牙语。默认为汉语
    # per: #每页说说的显示数量
    # placeholder1: #在编辑说说的输入框中的占位符
    # placeholder2: #自定义头像url的输入框的占位符
    # lazy: #加载动画的开关，1为开，0为关，默认为开
    # bgimg: #说说输入框背景图片url
    # color1: #说说背景颜色1&按钮颜色1
    # color2: #说说背景颜色2&按钮颜色2
    # color3: #说说字体颜色
  ##################################
  # 暗黑模式 darkmodejs
  # https://darkmodejs.learn.uno
  # 暗黑模式样式：https://github.com/volantis-x/hexo-theme-volantis/blob/master/source/css/_third-party/darkmode.styl
  darkmodejs:
    enable: true
    js: https://cdn.jsdelivr.net/npm/darkmode-js@1.5/lib/darkmode-js.min.js
    bottom: 32px
    right: unset
    left: 16px
    time: 0s
    mixColor: '#f4f4f4'
    backgroundColor: '#f4f4f4'
    buttonColorDark: '#100f2c'
    buttonColorLight: '#f4f4f4'
    saveInCookies: true
    label: 🌓
    autoMatchOsTheme: true



############################### Comments ###############################
comments:
  path:                    # 全局评论地址 仅支持 valine , miniValine , disqus , gitalk
  placeholder: 快来评论吧~  # 评论占位提示 仅支持 valine & miniValine
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: gitalk # valine, minivaline, disqus, gitalk, vssue, livere, isso, hashover
  # Valine
  # https://valine.js.org/
  valine: # 请将 appId appKey 修改为自己的，否则评论数据是共享的。
    appId: # your appId
    appKey: # your appKey
    # js: https://cdn.jsdelivr.net/npm/valine@1.4/dist/Valine.min.js
    meta: nick,mail,link # valine comment header info
    requiredFields: ['nick','mail']
    enableQQ: true # Unstable avatar link
    avatar: robohash # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    visitor: true
    mathJax: false
  # MiniValine
  # https://github.com/MiniValine/MiniValine
  minivaline:
    appId: # your appId
    appKey: # your appKey
    js: https://cdn.jsdelivr.net/npm/minivaline@3/dist/MiniValine.min.js
    mode: xCss # DesertsP or xCss
    math: false # Support MathJax.
    md: true # Support Markdown.
    enableQQ: false # Enable QQ avatar API.
    NoRecordIP: true # Do not record commenter IP.
    closeFlag: false
    closeUA: false
    region: false
    visitor: false # Article reading statistics.
    maxNest: 6 # Sub-comment maximum nesting depth.
    pageSize: 6 # Pagination size.
    barrager: 0
    role: admin
    cloudflag: false
    adminEmailMd5: de8a7aa53d07e6b6bceb45c64027763d # The MD5 of Admin Email to show Admin Flag.[ Just Only DesertsP Style mode]
    tagMeta: # The String Array of Words to show Flag.[ Just Only xCss Style mode]
      - 管理员
      - 小伙伴
      - 访客
    master: # The MD5 String Array of master Email to show master Flag.[ Just Only xCss Style mode]
      - de8a7aa53d07e6b6bceb45c64027763d
    friends: # The MD5 String Array of friends Email to show friends Flag. [ Just Only xCss Style mode]
      - b5bd5d836c7a0091aa8473e79ed4c25e
      - adb7d1cd192658a55c0ad22a3309cecf
      - 3ce1e6c77b4910f1871106cb30dc62b0
      - cfce8dc43725cc14ffcd9fb4892d5bfc
    # MiniValine's display language depends on user's browser or system environment
    # If you want everyone visiting your site to see a uniform language, you can set a force language value
    # Available values: en  | zh-CN | (and many more)
    # More i18n info: https://github.com/MiniValine/minivaline-i18n
    lang:
    # Expression Url.
    # https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-customize-emoticons
    emoticonUrl:
      - https://cdn.jsdelivr.net/npm/alus@latest
      - https://cdn.jsdelivr.net/gh/MiniValine/qq@latest
      - https://cdn.jsdelivr.net/gh/MiniValine/Bilibilis@latest
      - https://cdn.jsdelivr.net/gh/MiniValine/tieba@latest
      - https://cdn.jsdelivr.net/gh/MiniValine/twemoji@latest
      - https://cdn.jsdelivr.net/gh/MiniValine/weibo@latest
  # Disqus
  # https://disqus.com
  disqus:
    shortname:
    # optional
    autoload: false
  # Gitalk
  # https://gitalk.github.io/
  gitalk:
    clientID: 038184f3b131cbb8eafd
    clientSecret: 4daed04c4787d3df9d90981665b9b5345cb35314
    repo: zryyyy.github.io
    owner: zryyyy
    admin: zryyyy # []
  # Vssue
  # https://vssue.js.org/zh/
  vssue:
    owner:
    repo:
    clientId:
    clientSecret:
  # LiveRe
  # https://www.livere.com
  livere:
    uid:
  # Isso
  # https://posativ.org/isso/
  isso:
    url: https://example.com/(path/)
    src: https://example.com/(path/)js/embed.min.js
  # HashOver
  # https://www.barkdull.org/software/hashover
  hashover:
    src: https://example.com/(path/)comments.php

# 自定义右键菜单
rightmenu:
  enable: true
  # hr: 分割线, navigation: 导航按钮, music: 音乐控制器
  layout: [home, help, examples, contributors, hr, source_docs, source_theme, hr, print, hr, music]
  # 可选功能项
  print:
    name: 打印页面
    icon: fa fa-print
    onclick: document.execCommand('print')
  # 自定义菜单的格式如下
  help:
    name: 常见问题
    icon: fa fa-question
    url: https://volantis.js.org/faqs/
  examples:
    name: 示例博客
    icon: fa fa-rss
    url: https://volantis.js.org/examples/
  contributors:
    name: 加入社区
    icon: fa fa-fan fa-spin
    url: https://volantis.js.org/contributors/
  source_docs:
    name: 本站源码
    icon: fa fa-code-branch
    url: https://github.com/volantis-x/volantis-docs/
  source_theme:
    name: 主题源码
    icon: fa fa-code-branch
    url: https://github.com/volantis-x/hexo-theme-volantis/


############################### Search ###############################
# To use hexo search, you need to install the following plugins:
# npm i -S hexo-generator-search hexo-generator-json-content
search:
  enable: true
  service: hexo  # hexo, google, algolia, azure, baidu
  # js: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@3.0/js/search.js
  google:
    apiKey:
    engineId:
  algolia:
    applicationID:
    apiKey:
    indexName:
  azure:
    serviceName:
    indexName:
    queryKey:
  baidu:
    apiId:



############################### Theme Information ###############################
info:
  name: Volantis # This is theme's name.
  version: '3.0.0-rc.2' # This is theme's version.
  docs: https://volantis.js.org/ # This is theme's URL.
  repo: https://github.com/volantis-x/hexo-theme-volantis
  cdn:
    js:
    css:

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>
