### ISSUE TITLE
aplayer播完一首歌出现页面卡死

### ISSUE THREAD

**Issue by zmjddyq** [volantis-x/hexo-theme-volantis#445]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

A. 能正常运行，代表主题和当前环境配置都没有问题。
B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

- [ A] 测试结果是：A

## 问题描述

博客aplayer播完一首歌页面就卡死

### 复现地址
https://zmjddyq.gitee.io/

### 截图

<details><summary>相关截图</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
  aplayer:
    enable: true
    js:
      - https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.js
      - https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js
      - js/aplayer.js
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: song    # song, playlist, album, search, artist
    id: 29732992    # song id / playlist id / album id / search keyword
    # Optional
    fixed: true      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: false   # audio autoplay
    order: list       # player play order, values: 'list', 'random'
    loop: one         # player loop play, values: 'all', 'one', 'none'
    volume: 0.7       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 320px # list max height
    list_folded: true
```

#### node.js & npm
```
v14.5.0
6.14.5

```

#### package.json
```
hexo-site@0.0.0 E:\blog
+-- aplayer@1.10.1
+-- hexo@4.2.1
+-- hexo-asset-image@0.0.5 (git+https://github.com/CodeFalling/hexo-asset-image.git#3c114cf0c0343ab28469635085b225fcae7fb9d3)
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-pug@1.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-tag-aplayer@3.0.4
+-- hexo-theme-volantis@3.0.0-rc.2
`-- hexo-wordcount@6.0.1

```

</details>
