### ISSUE TITLE
import失败

### ISSUE THREAD

**Issue by zhanghuimeng** [volantis-x/hexo-theme-volantis#46]
尝试使用[import](https://xaoxuu.com/wiki/material-x/config/index.html#Import)功能时失败，配置文件如

```yaml
# 全局导入
import:
  meta:
    - "<meta name='theme-color' content='#FFFFFF'>"
    - "<meta name='msapplication-TileColor' content='#1BC3FB'>"
    - "<meta name='msapplication-config' content='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/browserconfig.xml'>"
  link:
    - "<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css'>"
    - "<link rel='shortcut icon' type='image/x-icon' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicon.ico'>"
    - "<link rel='icon' type='image/x-icon' sizes='32x32' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/favicon-32x32.png'>"
    - "<link rel='apple-touch-icon' type='image/png' sizes='180x180' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/apple-touch-icon.png'>"
    - "<link rel='mask-icon' color='#1BC3FB' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/safari-pinned-tab.svg'>"
    - "<link rel='manifest' href='https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicons/site.webmanifest'>"
```

时无法加载KaTeX新版本css。检查网页后发现`<head>`部分如下：

```html
  <!-- meta -->
  
  
  <meta name="undefined" content="">
  
  <meta name="undefined" content="">
  
  <meta name="undefined" content="">
  
  
  <!-- link -->
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css">
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.6.3/css/all.min.css">

  
  
  <link rel="undefined" href=""
  
  
  
  
  >
  
  <link rel="undefined" href=""
  
  
  
  
  >
  
  <link rel="undefined" href=""
  
  
  
  
  >
  
  <link rel="undefined" href=""
  
  
  
  
  >
  
  <link rel="undefined" href=""
  
  
  
  
  >
  
  <link rel="undefined" href=""
  
  
  
  
  >
  
  

  


  
  <link rel="stylesheet" href="/style.css">
```

感觉import功能好像都失败了。

已经检查过`import`位于子目录`_config.yml`文件中。
