### ISSUE TITLE
fontsize 修改后未生效

### ISSUE THREAD

**Issue by JonyFang** [volantis-x/hexo-theme-volantis#465]
## 预期与实际表现的区别

主题版本信息：

```
info:
  theme_name: Volantis # This is theme's name.
  theme_version: '4.0.0-rc.1' # This is theme's version.
  theme_docs: https://volantis.js.org/ # This is theme's URL.
  theme_repo: https://github.com/volantis-x/hexo-theme-volantis
```

修改的 fontsize 模块：

```
fontsize:
    root: 16px
    h1: 1.625rem
    h2: 1.5rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    body: .9375rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .75rem
```

根据需要调整 rootsize 后，未得到相应的修改结果。查阅文档未找到灵活的修改方式，辛苦校对~

## 如何复现这个问题

- [x] 在 Issues 中搜索不到相关问题。
- [x] 将主题升级至最新版本。
- [x] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

- [x] 详细的复现步骤

按照上述查看修改 __config.yml 文件可复现问题。

- [x] 具体的代码位置

按上述提到的 fontsize 搜索可以查看到

## 环境信息

主题版本信息：

```
info:
  theme_name: Volantis # This is theme's name.
  theme_version: '4.0.0-rc.1' # This is theme's version.
  theme_docs: https://volantis.js.org/ # This is theme's URL.
  theme_repo: https://github.com/volantis-x/hexo-theme-volantis
```

### 浏览器、操作系统

- Chrome 84.0.4147.135
- Mac OS 10.15.6

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml
fontsize:
    root: 18px
    h1: 1.625rem
    h2: 1.5rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    body: .9375rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .75rem
```

</details>

**Comment by xaoxuu** [comment]
我尝试了一下发现确实没有生效，主题中没有用到 root 这种尺寸，我稍后修复这个问题。

**Comment by JonyFang** [comment]
> 我尝试了一下发现确实没有生效，主题中没有用到 root 这种尺寸，我稍后修复这个问题。

修改 fontsize 里 root 的初衷是为了修改页面整理的字体大小。现在的页面在 电脑（Mac Chrome 浏览器）上的字体展示太小了，想做一个调整。修改 root 也是为了一次修改，各个模块对应调大，但发现没有生效。

如果想达到调整页面各层级字体的大小，除了修改这里的 root，还有其他的方式吗。

上面提到的`字体大小`指这些项的字体大小：
```
fontsize:
    root: 16px
    h1: 1.625rem
    h2: 1.5rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    body: .9375rem
    list: .9375rem
    meta: .875rem
    code: .8125rem
    footnote: .75rem
```
