### ISSUE TITLE
自定义右键菜单未生效

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#466]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

clone了最新的主题，在博客目录下创建了新的文件 _config.volantis.yml，并复制了主题配置文件里的自定义右键菜单到该文件中，具体可以看我提供的截图，hexo c && hexo s 后右键还是浏览器默认的样式，似乎未生效。

### 复现地址

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

![Snipaste_2020-08-30_12-45-26](https://user-images.githubusercontent.com/59497690/91651385-b3d52e80-eabe-11ea-80cc-71300867755e.png)
![Snipaste_2020-08-30_12-46-26](https://user-images.githubusercontent.com/59497690/91651392-d8c9a180-eabe-11ea-9603-74018dabddb3.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.volantis.yml` 中修改过的部分

```yml

rightmenu:
  enable: true
  # hr: 分割线, music: 音乐控制器
  layout: [home, categories, tags, archives, hr, friends, about, hr, music]
  # 可选功能项
  print:
    name: 打印页面
    icon: fa fa-print
    onclick: document.execCommand('print')
  # 自定义菜单的格式如下
  categories:
    name: 分类
    icon: fas fa-folder-open
    url: categories/
  tags:
    name: 标签
    icon: fas fa-tags
    url: tags/
  archives:
    name: 归档
    icon: fas fa-archive
    url: archives/
  friends:
    name: 友链
    icon: fas fa-link
    url: friends/
  about:
    name: 关于
    icon: fas fa-info-circle
    url: about/

```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```
v12.18.1
6.14.5
```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-qrcode@1.0.2
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
```

</details>
