### ISSUE TITLE
backstretch 功能打开后，改变窗口大小，图片不适配窗口尺寸 + 友链头像不显示

### ISSUE THREAD

**Issue by guguliu** [volantis-x/hexo-theme-volantis#475]
## 如何复现这个问题

- [x] 在 Issues 中搜索不到相关问题。
- [x] 将主题升级至最新版本。
- [x] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

- [x] 详细的复现步骤

backstretch问题:
1.主题的_config.yml 里面的 backstretch启用
2. 小窗口打开页面，图片显示正常
3. 最大化窗口，图片尺寸不适配窗口（如截图）

---------

友链头像问题：
- 根据 https://xaoxuu.com/wiki/volantis/page-settings/layout/ 的友链页面进行设置，用chrome浏览器friends页面后头像不显示，但是好像已经加载了。（如截图)
- /friends/index.md代码：
```
---
layout: friends
title: 我的朋友们
cover: true
sidebar: []
links:
  - group: 分组1
    icon: fas fa-user-tie
    desc: 这个分组的描述
    items:
    - name: Test
      avatar: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
      url: https://github.com/volantis-x/hexo-theme-volantis/tree/4.0.0-rc.2 
      backgroundColor: '#3E74C9'
      textColor: '#fff'
      tags: [标签1, 标签2]
      desc: 描述文字
  - group: 分组2
    icon: fas fa-user-tie
    desc: 这个分组的描述
    items:
    - name: Test2
      avatar: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
      url: https://www.baidu.com
      backgroundColor: '#3E74C9'
      textColor: '#fff'
      tags: [标签1, 标签2]
      desc: 描述文字
---
```

- [ ] 具体的代码位置

- [ ] 太优秀了，我可以提供Bug补丁

### 复现地址：

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址  

复现地址：https://guguliu.github.io/hexotest/

### 截图

<details><summary>相关截图:</summary>

![01](https://user-images.githubusercontent.com/32637322/92228671-d9a56d80-eeda-11ea-8972-a2dba7a5d796.jpg)

![02](https://user-images.githubusercontent.com/32637322/92228692-df02b800-eeda-11ea-892b-334cdc58e9a6.jpg)

![img](https://user-images.githubusercontent.com/32637322/92228711-e629c600-eeda-11ea-8eff-01b663bcbe48.jpg)

</details>

### 浏览器、操作系统

win10

主题版本：4.0.0-rc.2

测试浏览器：firefox 、chrome

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml
theme: volantis
```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml

backstretch:
    enable: true

```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```
PS C:\Users\liu> node -v
v12.16.2
PS C:\Users\liu> npm -v
6.14.4
```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```
+-- hexo@5.1.1
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.1.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@2.0.0
```

</details>

**Comment by guguliu** [comment]
头像那个解决了！
找到主题的配置文件`_config.yml`或者`_config.volantis.yml`里面的:
```yml
  # 图片懒加载
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true
    js: https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.1.0/dist/lazyload.min.js
    onlypost: false
    loadingImg: # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/placeholder/c617bfd2497fcea598e621413e315c368f8d8e.svg
    blurIn: true # 模糊加载效果 （loadingImg为空时有效）
```
把loadingImg：后面的图片链接注释删掉就正常了：
```yml
loadingImg: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/placeholder/c617bfd2497fcea598e621413e315c368f8d8e.svg
```
