### ISSUE TITLE
如何配置每篇文章的阅读量？

### ISSUE THREAD

**Issue by M00nBack** [volantis-x/hexo-theme-volantis#509]

**Comment by M00nBack** [comment]
![QQ截图20201001211617](https://user-images.githubusercontent.com/50912358/94816997-207d7900-042f-11eb-90a3-516e8723201c.png)
这个阅读量一直为0
![QQ截图20201001214430](https://user-images.githubusercontent.com/50912358/94817163-50c51780-042f-11eb-82c4-7b6f0790371b.png)
想问下在哪个能配置这个?找了半天没找到 还有 怎末把阅读量放到文章页面 
用的版本是：https://github.com/volantis-x/hexo-theme-volantis/releases/tag/3.0.0
非常感谢！！！

<blockquote><img src="https://avatars3.githubusercontent.com/u/68142033?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/volantis-x/hexo-theme-volantis/releases/tag/3.0.0">Release 3.0.0 · volantis-x/hexo-theme-volantis</a></strong></div><div>功能调整

U 搜索结果为相对路径，不再是绝对路径。
U 原 fancybox 标签改为 gallery 标签，使用方法不变。
U 不再支持多个评论系统共存，在主题配置文件中 comments.service 的值决定使用哪个评论系统。
U 置顶 top: true 改为了 pin: true 并且同样适用于 layout: page 的页面。

新增功能

A 支持 pjax。
A 支持 ...</div></blockquote>

**Comment by M00nBack** [comment]
找到了😂 打扰了

**Comment by M00nBack** [comment]
```
layout:
  # The following can be written in `blog/source/_data/layout.yml`
  # 文章列表（主页、自定义的列表）布局
  on_list:
    # 列表中每一篇文章的meta信息
    meta: [title, author, category, date, wordcount, counter, valinecount, pin]
    # 列表类页面的侧边栏
    sidebar: [blogger, category, tagcloud, qrcode]
    # read more button
    readmore: 阅读全文 <i class="fas fa-chevron-right"></i>
  # 页面布局
  on_page:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    meta:
      header: [title, author, category, date, wordcount , counter,valinecount, pin]
      footer: [updated, tags, btns, share]
    # 文章页面的侧边栏
    sidebar: [qrcode, toc]
  # 文章布局，参数继承自 on_page
  on_post:
    # 文章页脚，自动在每一篇文章末尾添加
    article_footer: [references, related_repos, copyright, donate]
  # 其他的页面布局暂时等于 on_list
```
改下面两个就行
```
meta: [title, author, category, date, wordcount, counter, valinecount, pin]
header: [title, author, category, date, wordcount , counter,valinecount, pin]
```
