### ISSUE TITLE
暗黑模式下搜索结果的字体颜色和白色混在一起了，看不见

### ISSUE THREAD

**Issue by LiYanan2004** [volantis-x/hexo-theme-volantis#52]
![image](https://user-images.githubusercontent.com/37542129/54768193-a533e800-4c39-11e9-9df8-1e1b0c1b9db1.png)

如果你发现 无法使用 或者效果与示例有较大区别，可以使用hexo官方提供的用于单元测试的博客应用本主题查看样式是否正常，对比_config.yml文件排查问题。

## 下载单元测试：

Hexo官方的单元测试博客： [https://github.com/hexojs/hexo-theme-unit-test.git](https://github.com/hexojs/hexo-theme-unit-test.git)。
如果你的系统是macOS，则可以使用hexo.sh脚本一键完成测试。

## 提问前请先认真阅读文档

文档：[https://xaoxuu.com/wiki/material-x/](https://xaoxuu.com/wiki/material-x/)

**Comment by LiYanan2004** [comment]
希望开发者能把Dark mode多加优化！还有好几处细节可以改进，比如：阅读原文那个我设置了主题色上颜色为黑色，但是依旧显示白色；热门标签里依旧有标签显示不出来.....

**Comment by xaoxuu** [comment]
我现在改一下

**Comment by xaoxuu** [comment]
@LiYanan2004 我修复了部分显示问题，但是侧边栏标签需要额外设置，我为`tagcloud`增加了两个字段用来设置标签云的最小字体颜色和最大字体颜色，你可以这样试一下：
```yaml
# 侧边栏小部件
widgets:
  - widget: tagcloud
    start_color: '#999'
    end_color: '#FFF'
```
