### ISSUE TITLE
_config.yml 中的 SEO 项 use_tags_as_keywords 不生效

### ISSUE THREAD

**Issue by richard4O4** [volantis-x/hexo-theme-volantis#522]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

> * `_config.yml` 中的 SEO 配置项里的 `use_tags_as_keywords` 并**没有起作用**，具体内容见**相关截图和配置文件**

### 复现地址

- [x] 文档官网源码和本地运行均存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

<img width="960" alt="1" src="https://user-images.githubusercontent.com/63702088/97077568-82d52e00-1617-11eb-9efd-04305ea03db4.png">

<img width="960" alt="2" src="https://user-images.githubusercontent.com/63702088/97077572-8a94d280-1617-11eb-8f32-47a60fa00f01.png">

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml
seo:
  # When there are no keywords in the article's front-matter, use tags as keywords.
  use_tags_as_keywords: true
  # When there is no description in the article's front-matter, use excerpt as the description.
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
    # robots can be written in front-matter
```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>
