### ISSUE TITLE
通过issues无法正常加载友链

### ISSUE THREAD

**Issue by hejojoiu** [volantis-x/hexo-theme-volantis#529]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [A ] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

放开主题_config.yml的issues: 

在友链的md文件中加上
{% issues sites | api=https://gitee.com/api/v5/repos/he-qizheng/blog_friends/issues?state=open&sort=created&direction=desc&page=1&per_page=100 %}   启动后无法加载出来友链的数据

## 环境信息 
volantis: 4.15
hexo-cli: 4.2.0
os: Linux 3.10.0-862.el7.x86_64 linux x64
node: 14.5.0
v8: 8.3.110.9-node.23
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 83
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2020a
unicode: 13.0
### 复现地址

- [ ] 文档官网源码本地运行存在异常。
- [x] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

![image](https://user-images.githubusercontent.com/46958050/98536574-fb4c1800-22c2-11eb-8269-04b833a2a48b.png)
![image](https://user-images.githubusercontent.com/46958050/98536597-02732600-22c3-11eb-8da9-56578aadda0c.png)
![image](https://user-images.githubusercontent.com/46958050/98536647-11f26f00-22c3-11eb-8c9d-0df424d2fca6.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml

  # 从 issues 加载动态数据
  # 例如：
  # {% issues sites | api=https://gitee.com/api/v5/repos/he-qizheng/blog_friends/issues?state=open&sort=created&direction=desc&page=1&per_page=100 %}  
  issues: 
    enable: true
    js: 

```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>
