### ISSUE TITLE
关于右键菜单问题

### ISSUE THREAD

**Issue by 2926295173** [volantis-x/hexo-theme-volantis#581]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [ ] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。
- [x] C. 由于demo版本未开启右键菜单，无法进行测试

## 问题描述

我的网站开启右键菜单后，发现4个图标展现异常，并且黑暗模式功能无效

## 环境信息 

win7,64
npm6.13.4
dependencies:
hexo-generator-archive: ^0.1.4
hexo-generator-category: ^0.1.3
hexo-generator-index: ^0.2.0
hexo-generator-tag: ^0.2.0
hexo-migrator-wordpress: ^0.1.2
hexo-renderer-ejs: ^0.2.0
hexo-renderer-marked: ^0.2.10
hexo-renderer-stylus: ^0.3.1
hexo-server: ^0.2.0
hexo: ^3.2.0
INFO  Validating config
hexo: 5.3.0
hexo-cli: 4.2.0
os: Windows_NT 6.1.7601 win32 x64
node: 12.16.1
v8: 7.8.279.23-node.31
uv: 1.34.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1

### 主题版本

您当前使用的版本为：_________4________

### 复现地址

aoian.cn
- [ ] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _______2926295173.github.io__________

### 截图

<details><summary>相关截图</summary>
![图片](https://user-images.githubusercontent.com/74408214/107014389-7f387200-67d6-11eb-9a1a-96820f80c0c1.png)

</details>

### 浏览器、操作系统
huohuiliulanqi,win7,64
### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml
title: 小高技术栈
subtitle: '技术天下'
description: '技术'
keywords:
author: aoian
language: zh-CN
timezone: 'Asia/Shanghai'

#图标文件
import:
  meta:
    - <meta name="msapplication-TileColor" content="#ffffff">
    - <meta name="msapplication-config" content="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/browserconfig.xml">
    - <meta name="theme-color" content="#ffffff">
  link:
    - <link rel="apple-touch-icon" sizes="180x180" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png">
    - <link rel="icon" type="image/png" sizes="32x32" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon-32x32.png">
    - <link rel="icon" type="image/png" sizes="16x16" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon-16x16.png">
    - <link rel="manifest" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/site.webmanifest">
    - <link rel="mask-icon" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/safari-pinned-tab.svg" color="#5bbad5">
    - <link rel="shortcut icon" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon.ico">

pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true 

```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml

clipboard:
    enable: true
    js: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
clipboard:
    enable: true
    js: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js

  ######## Plugins for SEO:

  # npm i hexo-wordcount
  wordcount:
    enable: true

  ######## Plugins for ...
  # Button Ripple Effect
  nodewaves:
    enable: true
    css: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.css
    js: https://cdn.jsdelivr.net/npm/node-waves@0.7.6/dist/waves.min.js

  # fontawesome animation
  fontawesome_animation:
    enable: true
    css: https://cdn.jsdelivr.net/gh/l-lin/font-awesome-animation/dist/font-awesome-animation.min.css

  # Typing Effects
  comment_typing:
    enable: true
    js: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@2/js/comment_typing.js

  # Slide Background
  backstretch:
    enable: true
```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```
hexo-site@0.0.0 D:\vscode\hexosite\blog
+-- hexo@5.3.0
+-- UNMET DEPENDENCY hexo-deployer-git@^2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.1
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.3.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- UNMET DEPENDENCY hexo-theme-landscape@0.0.3
+-- UNMET DEPENDENCY hexo-theme-volantis@4.3.1
`-- UNMET DEPENDENCY hexo-wordcount@^6.0.1

npm ERR! missing: hexo-theme-landscape@0.0.3, required by hexo-site@0.0.0
npm ERR! missing: hexo-theme-volantis@4.3.1, required by hexo-site@0.0.0
npm ERR! missing: hexo-deployer-git@^2.1.0, required by hexo-site@0.0.0
npm ERR! missing: hexo-wordcount@^6.0.1, required by hexo-site@0.0.0

```

</details>
