### ISSUE TITLE
自定义字体“EB Garamond”配置不生效

### ISSUE THREAD

**Issue by ilittlemoe** [volantis-x/hexo-theme-volantis#597]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [ ] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [x] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

我在主题配置文件中尝试自定义code字体和logo字体，当我使用EB Garamond字体时不生效，使用思源宋体却能生效。我确保我已经关闭了主题的“use_cdn: false”

### 主题版本

您当前使用的版本为：4.3.1

### 复现地址

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

![20210313_Snipaste_135825](https://user-images.githubusercontent.com/49776285/111020980-6ab64d80-8404-11eb-80a5-d30d8e067ff5.jpg)

</details>

### 浏览器、操作系统
浏览器：edge chrome版（最新版）、火狐ers。
操作系统：windows10 2024

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml
  fontfamily:
    logofont:
      font-family: '"EB Garamond", serif;'
      #name: '"EB Garamond"'
      url: https://cdn.jsdelivr.net/gh/ilittlemoe/cdn-font/EB_Garamond/static/EBGaramond-Bold.ttf
      #weight: normal
      style: Bold
    bodyfont:
      font-family: '"Noto Serif SC", serif;'
      #name: 'NotoSerifSC-Medium'
      url: https://cdn.jsdelivr.net/gh/ilittlemoe/cdn-font/Noto_Serif_SC/NotoSerifSC-Medium.otf
      #weight: normal
      #style: normal
    codefont:
      font-family: '"Noto Serif SC", serif;'
      #name: 'EBGaramond-Regular'
      url: https://cdn.jsdelivr.net/gh/ilittlemoe/cdn-font/Noto_Serif_SC/NotoSerifSC-Regular.otf
      #weight: normal
      #style: normal
```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```
$ npm -v
6.14.11

$ node -v
v14.16.0

```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```
$ npm ls --depth 0
hexo-site@0.0.0 D:\Blog\littlemoe
+-- gulp@4.0.2
+-- gulp-html-minifier-terser@6.0.1
+-- gulp-htmlclean@2.7.22
+-- gulp-htmlmin@5.0.1
+-- gulp-minify-css@1.2.4
+-- gulp-terser@2.0.1
+-- hexo@5.4.0
+-- hexo-deployer-git@3.0.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.1
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-related-popular-posts@5.0.1
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@4.0.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-theme-landscape@0.0.3
+-- hexo-theme-volantis@4.3.1
`-- live2d-widget-model-koharu@1.0.5

```

</details>

**Comment by xaoxuu** [comment]
没有名字是不会生效的：

![image](https://user-images.githubusercontent.com/16400144/111057838-538b6480-84c5-11eb-9fa3-c8d11fac2b3d.png)

加了名字就可以了：

![image](https://user-images.githubusercontent.com/16400144/111057858-7a499b00-84c5-11eb-8843-9060705d8a83.png)

**Comment by ilittlemoe** [comment]
> 没有名字是不会生效的：
> 
> ![image](https://user-images.githubusercontent.com/16400144/111057838-538b6480-84c5-11eb-9fa3-c8d11fac2b3d.png)
> 
> 加了名字就可以了：
> 
> ![image](https://user-images.githubusercontent.com/16400144/111057858-7a499b00-84c5-11eb-8843-9060705d8a83.png)
@xaoxuu
这真的很奇怪，我尝试修改成和你一样的，但是在我的博客上不会显示。然后我创建了一个全新的hexo init 然后克隆主题到node文件夹（npm i hexo-theme-volantis），并使用`_config.volantis.yml`这个文件作为自定义主题配置。我只在这个主题配置文件中加了下面的内容：
```yml
use_cdn: false
############################### Custom css ############################### > start
custom_css:
  fontfamily:
    logofont:
      font-family: '"EB Garamond", serif;'
      name: '"EB Garamond"'
      url: https://cdn.jsdelivr.net/gh/ilittlemoe/cdn-font/EB_Garamond/static/EBGaramond-Bold.ttf
      #weight: normal
      tyle: Bold
    bodyfont:
      font-family: '"Noto Serif SC", serif;'
      name: '"Noto Serif SC"'
      url: https://cdn.jsdelivr.net/gh/ilittlemoe/cdn-font/Noto_Serif_SC/NotoSerifSC-Medium.otf
      #weight: normal
      style: Medium
    codefont:
      font-family: '"Noto Serif SC", serif;'
      name: '"Noto Serif SC"'
      url: https://cdn.jsdelivr.net/gh/ilittlemoe/cdn-font/Noto_Serif_SC/NotoSerifSC-Regular.otf
      #weight: normal
      style: normal
############################### Custom css ############################### > end
```
其中`Style`这个项我反复尝试了几个，还有尝试注释掉，都是一样。是我的`name`写错了还是我的`url`不对呢？怎么就实现不了你这样的效果？还是说要部署到github上才会显示呢？请问你这个是在本地就出现的字体效果吗？

我也尝试过部署到github上，字体还是没有生效。这次说的情况是我克隆的一个全新的hexo环境测试的，并不是在我原来修改过的博客的文件的基础上做的。

最后感谢你百忙之中的解答和回复。
