### ISSUE TITLE
百度分析与谷歌分析无法生效 & gulp压缩失效 &修改友链样式出现报错

### ISSUE THREAD

**Issue by Aliroe** [volantis-x/hexo-theme-volantis#622]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述
百度分析与谷歌分析无法生效 & gulp压缩失效 &修改友链样式出现报错

以下是友链修改成traditional时，本地部署与在线部署都会出现以下报错<br>
```info
Unhandled rejection TypeError: O:\Desktop\Git-project\hexoblog\node_modules\hexo-theme-volantis\layout\friends.ejs:50
    48|                       <% if (item.keywords) { %>
    49|                         <div class='friend-tags-wrapper'>
    50|                         <% (item.keywords||[]).forEach(function(keyword){ %>
    51|                           <p class="tags"><i class="fas fa-hashtag fa-fw" aria-hidden="true"></i><%= keyword %></p>
    52|                         <% }) %>
    53|                         </div>

(item.keywords || []).forEach is not a function
    at eval (O:\Desktop\Git-project\hexoblog\node_modules\hexo-theme-volantis\layout\friends.ejs:110:28)
    at Array.forEach (<anonymous>)
    at eval (O:\Desktop\Git-project\hexoblog\node_modules\hexo-theme-volantis\layout\friends.ejs:86:26)
    at Array.forEach (<anonymous>)
    at eval (O:\Desktop\Git-project\hexoblog\node_modules\hexo-theme-volantis\layout\friends.ejs:32:26)
    at friends (O:\Desktop\Git-project\hexoblog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (O:\Desktop\Git-project\hexoblog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (O:\Desktop\Git-project\hexoblog\node_modules\hexo\lib\theme\view.js:39:17)
    at O:\Desktop\Git-project\hexoblog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (O:\Desktop\Git-project\hexoblog\node_modules\bluebird\js\release\util.js:16:23)
    at O:\Desktop\Git-project\hexoblog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (O:\Desktop\Git-project\hexoblog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:491:10)
    at resume_ (_stream_readable.js:976:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

gulp执行的时候代码压缩本地也无效

### 主题版本

您当前使用的版本为：4.3.1
Hexo版本：5.4.0

### 复现地址

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

![image](https://user-images.githubusercontent.com/40637160/115689604-d0e0a980-a38e-11eb-9f99-e8be44d2490a.png)
</details>

### 浏览器、操作系统
Chrome 稳定版 版本 90.0.4430.85（正式版本） （64 位）
Windows10专业版 20H2 19042.928
### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml
# Site
title: Zer0's Blog
subtitle: ''
description: (Zer0's Blog) 日常摸鱼记录 水文章的过程
keywords: 'Zer0,hexo,Zer0,ctf,CTF'
author: Zer0
language: zh-CN
timezone: 'Asia/Shanghai'
```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml
#数据分析
baidu_analytics_key: 612246419b5b9ddcaf936fdcf7e19c21 #百度统计的key
google_analytics_key: G-9KPKB15P85 #Google Analytics Key

```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```
$ node -v
v12.13.1
```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```
$ npm ls --depth 0
hexo-site@0.0.0 O:\Desktop\Git-project\hexoblog
+-- gulp@4.0.2
+-- gulp-html-minifier-terser@6.0.1
+-- gulp-htmlclean@2.7.22
+-- gulp-htmlmin@5.0.1
+-- gulp-imagemin@7.1.0
+-- gulp-minify-css@1.2.4
+-- gulp-terser@2.0.1
+-- gulp-uglify@3.0.2
+-- hexo@5.4.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.1
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.3.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-theme-landscape@0.0.3
+-- hexo-theme-volantis@4.3.1
+-- hexo-wordcount@6.0.1
`-- install@0.13.0
```

</details>

**Comment by inkss** [comment]
看起来像是友链的 keys 列出了问题，能提供下友链的配置内容吗？

**Comment by Aliroe** [comment]
友链的配置内容
```
- group: 朋友🧑 # 分组标题
  description: Friends # 分组描述
  items:
    - title: Wittoy’s Blog（篱落闲栈） # 名称
      avatar: https://cdn.jsdelivr.net/gh/1rz/static/images/me.jpg # 头像
      url: https://blog.wittoy.com/ # 链接
      keywords: 咕咕咕选手 # 关键词
      description: 摸鱼天下第一 # 描述
    - title: Keac's Blog # 名称
      avatar: https://www.loongten.com/avatar/keacwu.jpg # 头像
      url: http://www.loongten.com # 链接
      keywords: none # 关键词
      description: 路虽远，行则必达。事虽难，做则必成。 # 描述
    - title: RoarNyaの咸鱼窝 # 名称
      avatar: https://blog.ncsec.cn/upload/2020/04/avatar-d65453ce38db44389144e790d064ab8b.jpg # 头像
      url: https://blog.ncsec.cn/ # 链接
      keywords: None # 关键词
      description: None # 描述
    - title: AdianGg 's Blog # 名称
      avatar: https://assets.wgpsec.org/www/donation/A.jpg # 头像
      url: https://www.e-wolf.top/ # 链接
      keywords: none # 关键词
      description: none # 描述
    - title: 玉明 # 名称
      avatar: https://oss.xdym11235.com/JmN0a9.png # 头像
      url: https://xdym11235.com # 链接
      keywords: none # 关键词
      description: none # 描述
    - title: 思睿Sirui # 名称
      avatar: https://cdn.jsdelivr.net/gh/Siruirui/images/img/avatar.jpg # 头像
      url: https://Siruis.top # 链接
      keywords: none # 关键词
      description: none # 描述
    - title: H2AoiのBlog # 名称
      avatar: https://cdn.jsdelivr.net/gh/H2Aoi/tuchuang@master/img/666666.png # 头像
      url: https://blog.h2aoi.top/ # 链接
      keywords: none # 关键词
      description: none # 描述

- group: 安全 # 分组标题
  description: Security # 分组描述
  items:
    - title: Wgpsec安全团队 # 名称
      avatar: https://www.wgpsec.org/_nuxt/img/new_logo.7cc9e4f.svg # 头像
      url: https://www.wgpsec.org/ # 链接
      keywords: Wgpsewc # 关键词
      description: 致力于打造信息安全乌托邦 # 描述
```
